import { randomUUID } from "node:crypto";
import { once } from "node:events";
import { mkdtemp,tmpdir,path,DatabaseSync,expect,test,electron,continueFromMain,removeVerifiedTemporaryDirectory,type Page } from "./support/desktop-shell-suite";

type RunningElectron=Awaited<ReturnType<typeof electron.launch>>;
function diagnostics(app:RunningElectron):void{app.process().stderr?.on("data",(chunk)=>process.stderr.write(`[snapshot-scene-e2e stderr] ${String(chunk)}`));}
async function closeElectron(app:RunningElectron):Promise<void>{const child=app.process();const closed=await Promise.race([app.close().then(()=>true,()=>true),new Promise<false>((resolve)=>setTimeout(()=>resolve(false),8_000))]);if(!closed&&child.exitCode===null&&child.signalCode===null){const exit=once(child,"exit").catch(()=>undefined);child.kill("SIGKILL");await exit;}}
async function openVersion(page:Page):Promise<void>{await page.getByRole("navigation",{name:"작품 작업면"}).getByRole("button",{name:"검토",exact:true}).click();const workspace=page.getByRole("region",{name:"검토 작업"});await workspace.getByRole("tab",{name:"버전",exact:true}).click();await expect(workspace.getByRole("tab",{name:"버전",exact:true})).toHaveAttribute("aria-selected","true");}
async function finalizeCurrentScene(page:Page):Promise<string>{return page.evaluate(async()=>{const catalog=await window.eumStudio.workspace.getCatalog();if(catalog.activeWorkId===null)throw new Error("Expected Work");const projection=await window.eumStudio.structure.listSceneProjection({schemaVersion:1,workId:catalog.activeWorkId});const scene=projection.scenes.find((candidate)=>candidate.range!==null&&candidate.integrity==="resolved");if(scene===undefined||scene.range===null)throw new Error("Expected resolved Scene");const result=await window.eumStudio.structure.finalizeSceneCanonCheck({schemaVersion:1,workId:catalog.activeWorkId,sceneKey:scene.sceneKey,documentId:scene.documentId,documentRevisionId:scene.documentRevisionId,from:scene.range.start,to:scene.range.end});return result.sceneId;});}

test("groups immutable WorkSnapshots into named slots and keeps Scene selection planning read-only",async()=>{
  test.setTimeout(150_000);const directory=await mkdtemp(path.join(tmpdir(),"eum-snapshot-scenes-e2e-"));const suffix=randomUUID().slice(0,8);const slotName=`대체 전개 ${suffix}`;const firstText=`윤서는 북문을 열었다 ${suffix}.`;const secondText=`윤서는 북문을 닫았다 ${suffix}.`;
  const args=[".",`--user-data-dir=${path.join(directory,"electron-user-data")}`];const env={...process.env,EUM_STUDIO_TEST_EPHEMERAL_WORKSPACE:"0",EUM_STUDIO_LOCAL_WORKSPACE_ROOT_PATH:directory,EUM_STUDIO_WINDOW_VISIBILITY:"hidden",EUM_STUDIO_DISABLE_SANDBOX:"1"};let app=await electron.launch({args,cwd:process.cwd(),env});diagnostics(app);let complete=false;
  try{let page=await app.firstWindow();await page.setViewportSize({width:1280,height:850});await page.getByRole("button",{name:"작품 만들기",exact:true}).click();const dialog=page.getByRole("dialog",{name:"새 작품 만들기"});await dialog.getByLabel("작품 제목").fill(`기준점 작품 ${suffix}`);await dialog.getByLabel("첫 회차 제목").fill("1화");await dialog.getByRole("button",{name:"작품 만들기",exact:true}).click();const manuscript=page.getByRole("textbox",{name:"원고"});await manuscript.pressSequentially(firstText);await expect(page.getByTestId("save-state")).toHaveText("저장됨");const firstSceneId=await finalizeCurrentScene(page);
    await openVersion(page);let slots=page.getByRole("region",{name:"명명된 기준점 슬롯",exact:true});await slots.getByLabel("기준점 슬롯 이름").fill(slotName);await slots.getByRole("button",{name:"이 슬롯에 기준점 만들기",exact:true}).click();await expect(slots.getByText(slotName,{exact:true})).toBeVisible();
    await page.getByRole("navigation",{name:"작품 작업면"}).getByRole("button",{name:"쓰기",exact:true}).click();await manuscript.click();await manuscript.press("Control+A");await manuscript.pressSequentially(secondText);await expect(page.getByTestId("save-state")).toHaveText("저장됨");const secondSceneId=await finalizeCurrentScene(page);expect(secondSceneId).not.toBe(firstSceneId);
    await openVersion(page);slots=page.getByRole("region",{name:"명명된 기준점 슬롯",exact:true});await slots.getByLabel("기준점 슬롯 이름").fill(slotName);await slots.getByRole("button",{name:"이 슬롯에 기준점 만들기",exact:true}).click();await expect(slots).toContainText("이전 기준점 1개 보존");await slots.getByText("이전 기준점 이력",{exact:true}).click();await slots.getByRole("button",{name:"이 기준점 비교",exact:true}).click();
    const comparison=page.getByRole("dialog",{name:"작품 스냅샷 비교"});await expect(comparison).toContainText("장면 단위 선택 plan");await expect(comparison).toContainText("자동 전체 병합과 부분 적용은 비활성화");await expect(comparison).toContainText(firstText);await expect(comparison).toContainText(secondText);await expect(comparison).toContainText("적용 명령 없음 · 자동 병합 금지");await expect(comparison.getByRole("button",{name:/병합|적용/u})).toHaveCount(0);
    const selectable=comparison.locator('.snapshot-scene-plan input[type="checkbox"]:not(:disabled)').first();await expect(selectable).toBeVisible();await selectable.click();await expect(comparison).toContainText("선택 1개");
    await comparison.getByRole("button",{name:"작품 스냅샷 비교 닫기",exact:true}).click();await closeElectron(app);app=await electron.launch({args,cwd:process.cwd(),env});diagnostics(app);page=await app.firstWindow();await page.setViewportSize({width:1280,height:850});await continueFromMain(page);await openVersion(page);slots=page.getByRole("region",{name:"명명된 기준점 슬롯",exact:true});await expect(slots.getByText(slotName,{exact:true})).toBeVisible();await expect(slots).toContainText("이전 기준점 1개 보존");complete=true;
  }finally{await closeElectron(app).catch(()=>undefined);if(complete){const audit=new DatabaseSync(path.join(directory,"workspace.sqlite3"),{readOnly:true});try{expect(audit.prepare(`SELECT (SELECT COUNT(*) FROM work_snapshots) AS snapshots,(SELECT COUNT(DISTINCT label) FROM work_snapshots) AS slots,(SELECT COUNT(*) FROM document_revisions) AS revisions,(SELECT COUNT(*) FROM pragma_foreign_key_check) AS foreignKeyViolations`).get()).toMatchObject({snapshots:2,slots:1,foreignKeyViolations:0});const manifests=audit.prepare(`SELECT structure_revision_refs_json AS manifest FROM work_snapshots ORDER BY created_at`).all() as {manifest:string}[];expect(manifests.every((row)=>JSON.parse(row.manifest).some((entry:{entityKind?:string})=>entry.entityKind==="SceneSnapshotManifest"))).toBe(true);}finally{audit.close();}}await removeVerifiedTemporaryDirectory(directory);}
});
