import type { LocalWorkspaceRuntime,LocalWorkspaceRuntimeOptions } from "./contracts";

import { WorkspaceOperationCoordinator } from "./operation-coordinator";
import { createWorkspaceReviewServices } from "./review-services";
import { ActivityService } from "./services/activity";
import { AnalysisService } from "./services/analysis";
import { AssistantService } from "./services/assistant";
import { BackupService } from "./services/backup";
import { CanonicalExportService } from "./services/canonical-export";
import { CharacterLoreService } from "./services/character-lore";
import { EventRailService } from "./services/event-rail";
import { EventsService } from "./services/events";
import { ForeshadowingService } from "./services/foreshadowing";
import { FragmentsService } from "./services/fragments";
import { InfrastructureService } from "./services/infrastructure";
import { ManuscriptAnnotationsService } from "./services/manuscript-annotations";
import { ManuscriptCoreService } from "./services/manuscript-core";
import { ManuscriptHistoryService } from "./services/manuscript-history";
import { ManuscriptResumeService } from "./services/manuscript-resume";
import { ManuscriptTransferService } from "./services/manuscript-transfer";
import { MusicService } from "./services/music";
import { PlotsService } from "./services/plots";
import { PublishingService } from "./services/publishing";
import { SceneAnnotationsService } from "./services/scene-annotations";
import { SceneGeometryService } from "./services/scene-geometry";
import { SceneTrashService } from "./services/scene-trash";
import { SettingsService } from "./services/settings";
import { WorkspaceService } from "./services/workspace";
import { WorkspaceRuntimeState } from "./state";
import type { WorkspaceStorage } from "./storage";

export function composeWorkspaceRuntime(storage: WorkspaceStorage, options: LocalWorkspaceRuntimeOptions) {
  const state = new WorkspaceRuntimeState(storage);
  const operations = new WorkspaceOperationCoordinator();
  const infrastructure = new InfrastructureService({
    state: state,
    database: storage.database,
    ledger: storage.ledger,
  });
  const events = new EventsService({
    state: state,
    operations: operations,
    ledger: storage.ledger,
    database: storage.database,
    options: options,
    revisionStore: storage.revisionStore,
    infrastructure: infrastructure,
  });
  const scene_geometry = new SceneGeometryService({
    state: state,
    operations: operations,
    database: storage.database,
    ledger: storage.ledger,
    options: options,
    revisionStore: storage.revisionStore,
    infrastructure: infrastructure,
    events: events,
  });
  const manuscript_core = new ManuscriptCoreService({
    state: state,
    operations: operations,
    database: storage.database,
    options: options,
    revisionStore: storage.revisionStore,
    infrastructure: infrastructure,
  });
  const settings = new SettingsService({
    state: state,
    operations: operations,
    options: options,
    database: storage.database,
    infrastructure: infrastructure,
  });
  const fragments = new FragmentsService({
    state: state,
    operations: operations,
    options: options,
    database: storage.database,
    revisionStore: storage.revisionStore,
    ledger: storage.ledger,
    infrastructure: infrastructure,
  });
  const foreshadowing = new ForeshadowingService({
    state: state,
    operations: operations,
    options: options,
    ledger: storage.ledger,
    database: storage.database,
    revisionStore: storage.revisionStore,
    infrastructure: infrastructure,
  });
  const character_lore = new CharacterLoreService({
    state: state,
    operations: operations,
    database: storage.database,
    revisionStore: storage.revisionStore,
    ledger: storage.ledger,
    options: options,
    infrastructure: infrastructure,
  });
  const scene_annotations = new SceneAnnotationsService({
    operations: operations,
    database: storage.database,
    infrastructure: infrastructure,
  });
  const assistant = new AssistantService({
    state: state,
    operations: operations,
    options: options,
    database: storage.database,
    revisionStore: storage.revisionStore,
    ledger: storage.ledger,
    infrastructure: infrastructure,
    character_lore: character_lore,
    scene_geometry: scene_geometry,
    scene_annotations: scene_annotations,
    settings: settings,
  });
  const workspace = new WorkspaceService({
    state: state,
    operations: operations,
    database: storage.database,
    blobStore: storage.blobStore,
    blobProfile: storage.blobProfile,
    ledger: storage.ledger,
    options: options,
    revisionStore: storage.revisionStore,
    infrastructure: infrastructure,
  });
  const manuscript_resume = new ManuscriptResumeService({
    state: state,
    operations: operations,
    database: storage.database,
    ledger: storage.ledger,
    revisionStore: storage.revisionStore,
    options: options,
    infrastructure: infrastructure,
  });
  const plots = new PlotsService({
    state: state,
    operations: operations,
    database: storage.database,
    options: options,
    ledger: storage.ledger,
    revisionStore: storage.revisionStore,
    infrastructure: infrastructure,
    events: events,
  });
  const event_rail = new EventRailService({
    state: state,
    operations: operations,
    infrastructure: infrastructure,
    events: events,
    plots: plots,
  });
  const music = new MusicService({
    state: state,
    operations: operations,
    options: options,
    database: storage.database,
    ledger: storage.ledger,
    infrastructure: infrastructure,
    scene_geometry: scene_geometry,
  });
  const scene_trash = new SceneTrashService({
    state: state,
    operations: operations,
    database: storage.database,
    options: options,
    sceneTrashStore: storage.sceneTrashStore,
    revisionStore: storage.revisionStore,
    infrastructure: infrastructure,
    scene_geometry: scene_geometry,
    scene_annotations: scene_annotations,
    music: music,
    manuscript_core: manuscript_core,
    workspace: workspace,
  });
  const manuscript_annotations = new ManuscriptAnnotationsService({
    state: state,
    operations: operations,
    database: storage.database,
    revisionStore: storage.revisionStore,
    ledger: storage.ledger,
    options: options,
    infrastructure: infrastructure,
  });
  const publishing = new PublishingService({
    state: state,
    operations: operations,
    database: storage.database,
    ledger: storage.ledger,
    options: options,
    infrastructure: infrastructure,
  });
  const activity = new ActivityService({
    state: state,
    operations: operations,
    options: options,
    database: storage.database,
    ledger: storage.ledger,
    revisionStore: storage.revisionStore,
    infrastructure: infrastructure,
    settings: settings,
  });
  const manuscript_history = new ManuscriptHistoryService({
    state: state,
    operations: operations,
    database: storage.database,
    revisionStore: storage.revisionStore,
    ledger: storage.ledger,
    infrastructure: infrastructure,
    workspace: workspace,
    scene_geometry: scene_geometry,
  });
  const reviews = createWorkspaceReviewServices({
    database: storage.database, ledger: storage.ledger, revisionStore: storage.revisionStore,
    state, options, authorizeContext: assistant.authorizeAssistantContextAccessSerially.bind(assistant),
  });
  const analysis = new AnalysisService({
    state: state,
    operations: operations,
    options: options,
    canonService: reviews.canonService,
    contextPlanner: reviews.contextPlanner,
    continuityService: reviews.continuityService,
    characterKnowledgeService: reviews.characterKnowledgeService,
    narrativeDigestService: reviews.narrativeDigestService,
    database: storage.database,
    infrastructure: infrastructure,
  });
  const canonical_export = new CanonicalExportService({
    operations: operations,
    continuityService: reviews.continuityService,
    characterKnowledgeService: reviews.characterKnowledgeService,
    infrastructure: infrastructure,
    workspace: workspace,
    character_lore: character_lore,
    events: events,
    plots: plots,
    foreshadowing: foreshadowing,
    scene_geometry: scene_geometry,
    scene_annotations: scene_annotations,
  });
  const backup = new BackupService({
    operations: operations,
    backupService: storage.backupService,
    infrastructure: infrastructure,
  });
  const manuscript_transfer = new ManuscriptTransferService({
    state: state,
    operations: operations,
    database: storage.database,
    options: options,
    episodeRangeMoveStore: storage.episodeRangeMoveStore,
    revisionStore: storage.revisionStore,
    infrastructure: infrastructure,
    scene_geometry: scene_geometry,
    manuscript_core: manuscript_core,
    workspace: workspace,
  });
  const facade: LocalWorkspaceRuntime = {
    getWorkspaceCatalog: workspace.getWorkspaceCatalog.bind(workspace),
    getDocumentCompletion: manuscript_core.getDocumentCompletion.bind(manuscript_core),
    completeDocument: manuscript_core.completeDocument.bind(manuscript_core),
    clearDocumentCompletion: manuscript_core.clearDocumentCompletion.bind(manuscript_core),
    getWorkFavorites: workspace.getWorkFavorites.bind(workspace),
    setWorkFavorite: workspace.setWorkFavorite.bind(workspace),
    getWorkCovers: workspace.getWorkCovers.bind(workspace),
    saveWorkCover: workspace.saveWorkCover.bind(workspace),
    activateWorkspaceLocation: workspace.activateWorkspaceLocation.bind(workspace),
    renameWork: workspace.renameWork.bind(workspace),
    renameDocument: workspace.renameDocument.bind(workspace),
    retireWork: workspace.retireWork.bind(workspace),
    retireDocument: workspace.retireDocument.bind(workspace),
    retireAllDocuments: workspace.retireAllDocuments.bind(workspace),
    moveDocument: workspace.moveDocument.bind(workspace),
    createDocumentFolder: workspace.createDocumentFolder.bind(workspace),
    renameDocumentFolder: workspace.renameDocumentFolder.bind(workspace),
    placeDocumentInFolder: workspace.placeDocumentInFolder.bind(workspace),
    retireDocumentFolder: workspace.retireDocumentFolder.bind(workspace),
    getManuscriptDocumentProfile: manuscript_core.getManuscriptDocumentProfile.bind(manuscript_core),
    getContinuousReadingProgress: settings.getContinuousReadingProgress.bind(settings),
    saveContinuousReadingProgress: settings.saveContinuousReadingProgress.bind(settings),
    getManuscriptPersistenceProfile: manuscript_core.getManuscriptPersistenceProfile.bind(manuscript_core),
    getManuscriptStartupRecovery: manuscript_core.getManuscriptStartupRecovery.bind(manuscript_core),
    getManuscriptResumeCheckpoint: manuscript_resume.getManuscriptResumeCheckpoint.bind(manuscript_resume),
    captureWorkspaceResume: manuscript_resume.captureWorkspaceResume.bind(manuscript_resume),
    createEventBlock: events.createEventBlock.bind(events),
    createAnchorlessEvent: events.createAnchorlessEvent.bind(events),
    moveEventBlock: events.moveEventBlock.bind(events),
    linkEventSource: events.linkEventSource.bind(events),
    replaceEventSource: events.replaceEventSource.bind(events),
    retireEventSource: events.retireEventSource.bind(events),
    listEventBlocks: events.listEventBlocks.bind(events),
    listEventRail: event_rail.listEventRail.bind(event_rail),
    createSceneOverride: scene_geometry.createSceneOverride.bind(scene_geometry),
    relocateSceneSegment: scene_geometry.relocateSceneSegment.bind(scene_geometry),
    listSceneOverrides: scene_geometry.listSceneOverrides.bind(scene_geometry),
    listSceneProjection: scene_geometry.listSceneProjection.bind(scene_geometry),
    listSceneCanonContexts: scene_geometry.listSceneCanonContexts.bind(scene_geometry),
    finalizeSceneCanonCheck: scene_geometry.finalizeSceneCanonCheck.bind(scene_geometry),
    updateSceneRuleSet: scene_geometry.updateSceneRuleSet.bind(scene_geometry),
    setSceneEventOverride: scene_geometry.setSceneEventOverride.bind(scene_geometry),
    rebindSceneMetadata: scene_geometry.rebindSceneMetadata.bind(scene_geometry),
    prepareSceneDeletion: scene_trash.prepareSceneDeletion.bind(scene_trash),
    deleteScene: scene_trash.deleteScene.bind(scene_trash),
    listSceneTrash: scene_trash.listSceneTrash.bind(scene_trash),
    restoreSceneTrash: scene_trash.restoreSceneTrash.bind(scene_trash),
    undoSceneDeletion: scene_trash.undoSceneDeletion.bind(scene_trash),
    captureFragment: fragments.captureFragment.bind(fragments),
    listFragments: fragments.listFragments.bind(fragments),
    updateFragment: fragments.updateFragment.bind(fragments),
    recordFragmentUse: fragments.recordFragmentUse.bind(fragments),
    retireFragment: fragments.retireFragment.bind(fragments),
    createManuscriptAnnotation: manuscript_annotations.createManuscriptAnnotation.bind(manuscript_annotations),
    listManuscriptAnnotations: manuscript_annotations.listManuscriptAnnotations.bind(manuscript_annotations),
    updateManuscriptAnnotation: manuscript_annotations.updateManuscriptAnnotation.bind(manuscript_annotations),
    retireManuscriptAnnotation: manuscript_annotations.retireManuscriptAnnotation.bind(manuscript_annotations),
    createCharacter: character_lore.createCharacter.bind(character_lore),
    listCharacters: character_lore.listCharacters.bind(character_lore),
    updateCharacter: character_lore.updateCharacter.bind(character_lore),
    addCharacterEvidence: character_lore.addCharacterEvidence.bind(character_lore),
    retireCharacter: character_lore.retireCharacter.bind(character_lore),
    createCharacterRelation: character_lore.createCharacterRelation.bind(character_lore),
    listCharacterRelations: character_lore.listCharacterRelations.bind(character_lore),
    updateCharacterRelation: character_lore.updateCharacterRelation.bind(character_lore),
    retireCharacterRelation: character_lore.retireCharacterRelation.bind(character_lore),
    createLoreEntry: character_lore.createLoreEntry.bind(character_lore),
    listLoreEntries: character_lore.listLoreEntries.bind(character_lore),
    updateLoreEntry: character_lore.updateLoreEntry.bind(character_lore),
    addLoreEntryEvidence: character_lore.addLoreEntryEvidence.bind(character_lore),
    retireLoreEntry: character_lore.retireLoreEntry.bind(character_lore),
    linkLoreForeshadow: character_lore.linkLoreForeshadow.bind(character_lore),
    listLoreForeshadowLinks: character_lore.listLoreForeshadowLinks.bind(character_lore),
    unlinkLoreForeshadow: character_lore.unlinkLoreForeshadow.bind(character_lore),
    createLoreCandidate: character_lore.createLoreCandidate.bind(character_lore),
    listLoreCandidates: character_lore.listLoreCandidates.bind(character_lore),
    approveLoreCandidate: character_lore.approveLoreCandidate.bind(character_lore),
    rejectLoreCandidate: character_lore.rejectLoreCandidate.bind(character_lore),
    createPublishingPartner: publishing.createPublishingPartner.bind(publishing),
    listPublishingPartners: publishing.listPublishingPartners.bind(publishing),
    updatePublishingPartner: publishing.updatePublishingPartner.bind(publishing),
    createPublishingFormTemplate: publishing.createPublishingFormTemplate.bind(publishing),
    listPublishingFormTemplates: publishing.listPublishingFormTemplates.bind(publishing),
    updatePublishingFormTemplate: publishing.updatePublishingFormTemplate.bind(publishing),
    listPublishingFormResponses: publishing.listPublishingFormResponses.bind(publishing),
    savePublishingFormResponse: publishing.savePublishingFormResponse.bind(publishing),
    createPublishingSubmission: publishing.createPublishingSubmission.bind(publishing),
    listPublishingSubmissions: publishing.listPublishingSubmissions.bind(publishing),
    updatePublishingSubmission: publishing.updatePublishingSubmission.bind(publishing),
    createPublishingContract: publishing.createPublishingContract.bind(publishing),
    listPublishingContracts: publishing.listPublishingContracts.bind(publishing),
    updatePublishingContract: publishing.updatePublishingContract.bind(publishing),
    createPublishingPublication: publishing.createPublishingPublication.bind(publishing),
    listPublishingPublications: publishing.listPublishingPublications.bind(publishing),
    updatePublishingPublication: publishing.updatePublishingPublication.bind(publishing),
    createPublishingSettlement: publishing.createPublishingSettlement.bind(publishing),
    listPublishingSettlements: publishing.listPublishingSettlements.bind(publishing),
    updatePublishingSettlement: publishing.updatePublishingSettlement.bind(publishing),
    createPublishingPayment: publishing.createPublishingPayment.bind(publishing),
    listPublishingPayments: publishing.listPublishingPayments.bind(publishing),
    updatePublishingPayment: publishing.updatePublishingPayment.bind(publishing),
    createPublishingSource: publishing.createPublishingSource.bind(publishing),
    listPublishingSources: publishing.listPublishingSources.bind(publishing),
    previewPublishingResearch: publishing.previewPublishingResearch.bind(publishing),
    approvePublishingResearch: publishing.approvePublishingResearch.bind(publishing),
    runPublishingAssistant: publishing.runPublishingAssistant.bind(publishing),
    approvePublishingAssistantCandidate: publishing.approvePublishingAssistantCandidate.bind(publishing),
    setPublishingEvidenceLinks: publishing.setPublishingEvidenceLinks.bind(publishing),
    applyPublishingPartnerCsvImport: publishing.applyPublishingPartnerCsvImport.bind(publishing),
    applyPublishingSubmissionCsvImport: publishing.applyPublishingSubmissionCsvImport.bind(publishing),
    recordPublishingMailCandidate: publishing.recordPublishingMailCandidate.bind(publishing),
    listPublishingMailCandidates: publishing.listPublishingMailCandidates.bind(publishing),
    linkPublishingMailCandidate: publishing.linkPublishingMailCandidate.bind(publishing),
    updatePublishingMailCandidate: publishing.updatePublishingMailCandidate.bind(publishing),
    reviewPublishingMailCandidate: publishing.reviewPublishingMailCandidate.bind(publishing),
    createPlotThread: plots.createPlotThread.bind(plots),
    listPlotThreads: plots.listPlotThreads.bind(plots),
    getDefaultPlotBoard: plots.getDefaultPlotBoard.bind(plots),
    movePlotPlacement: plots.movePlotPlacement.bind(plots),
    setPlotPlacementStoryTime: plots.setPlotPlacementStoryTime.bind(plots),
    updatePlotThread: plots.updatePlotThread.bind(plots),
    retirePlotThread: plots.retirePlotThread.bind(plots),
    createPlotFromEvent: plots.createPlotFromEvent.bind(plots),
    createEventFromPlot: plots.createEventFromPlot.bind(plots),
    linkPlotEvent: plots.linkPlotEvent.bind(plots),
    unlinkPlotEvent: plots.unlinkPlotEvent.bind(plots),
    listPlotEventLinks: plots.listPlotEventLinks.bind(plots),
    linkPlotThreadSource: plots.linkPlotThreadSource.bind(plots),
    listPlotThreadSources: plots.listPlotThreadSources.bind(plots),
    createForeshadowLine: foreshadowing.createForeshadowLine.bind(foreshadowing),
    listForeshadowLines: foreshadowing.listForeshadowLines.bind(foreshadowing),
    updateForeshadowLine: foreshadowing.updateForeshadowLine.bind(foreshadowing),
    retireForeshadowLine: foreshadowing.retireForeshadowLine.bind(foreshadowing),
    createForeshadowPoint: foreshadowing.createForeshadowPoint.bind(foreshadowing),
    listForeshadowPoints: foreshadowing.listForeshadowPoints.bind(foreshadowing),
    startWritingSession: activity.startWritingSession.bind(activity),
    stopWritingSession: activity.stopWritingSession.bind(activity),
    startFocusCycle: activity.startFocusCycle.bind(activity),
    stopFocusCycle: activity.stopFocusCycle.bind(activity),
    listWorkActivity: activity.listWorkActivity.bind(activity),
    getPomodoro: activity.getPomodoro.bind(activity),
    configureAndStartPomodoro: activity.configureAndStartPomodoro.bind(activity),
    pausePomodoro: activity.pausePomodoro.bind(activity),
    resumePomodoro: activity.resumePomodoro.bind(activity),
    reconcilePomodoro: activity.reconcilePomodoro.bind(activity),
    updatePomodoroNote: activity.updatePomodoroNote.bind(activity),
    stopPomodoro: activity.stopPomodoro.bind(activity),
    prepareWorkRecordsExport: activity.prepareWorkRecordsExport.bind(activity),
    listDocumentRevisions: manuscript_history.listDocumentRevisions.bind(manuscript_history),
    readDocumentRevision: manuscript_history.readDocumentRevision.bind(manuscript_history),
    restoreDocumentRevision: manuscript_history.restoreDocumentRevision.bind(manuscript_history),
    createWorkSnapshot: manuscript_history.createWorkSnapshot.bind(manuscript_history),
    listWorkSnapshots: manuscript_history.listWorkSnapshots.bind(manuscript_history),
    compareWorkSnapshot: manuscript_history.compareWorkSnapshot.bind(manuscript_history),
    planWorkSnapshotSceneSelection: manuscript_history.planWorkSnapshotSceneSelection.bind(manuscript_history),
    getWorkRecordsGoals: settings.getWorkRecordsGoals.bind(settings),
    saveWorkRecordsGoals: settings.saveWorkRecordsGoals.bind(settings),
    getWorkReadthrough: settings.getWorkReadthrough.bind(settings),
    saveWorkReadthrough: settings.saveWorkReadthrough.bind(settings),
    listWorkSchedule: activity.listWorkSchedule.bind(activity),
    listWorkCalendar: activity.listWorkCalendar.bind(activity),
    getStudioToday: activity.getStudioToday.bind(activity),
    createWorkScheduleItem: activity.createWorkScheduleItem.bind(activity),
    updateWorkScheduleItem: activity.updateWorkScheduleItem.bind(activity),
    retireWorkScheduleItem: activity.retireWorkScheduleItem.bind(activity),
    setWorkScheduleCompletion: activity.setWorkScheduleCompletion.bind(activity),
    getAppSettings: settings.getAppSettings.bind(settings),
    saveAppSettings: settings.saveAppSettings.bind(settings),
    getWorkManuscriptLayoutSettings: settings.getWorkManuscriptLayoutSettings.bind(settings),
    saveWorkManuscriptLayoutSettings: settings.saveWorkManuscriptLayoutSettings.bind(settings),
    getWorkMusicSettings: music.getWorkMusicSettings.bind(music),
    saveWorkMusicSettings: music.saveWorkMusicSettings.bind(music),
    getWorkSceneAnalysisSettings: analysis.getWorkSceneAnalysisSettings.bind(analysis),
    saveWorkSceneAnalysisSettings: analysis.saveWorkSceneAnalysisSettings.bind(analysis),
    getWorkInspirationSettings: settings.getWorkInspirationSettings.bind(settings),
    saveWorkInspirationSettings: settings.saveWorkInspirationSettings.bind(settings),
    getWorkQuickMemo: settings.getWorkQuickMemo.bind(settings),
    saveWorkQuickMemo: settings.saveWorkQuickMemo.bind(settings),
    listAssistantContextState: assistant.listAssistantContextState.bind(assistant),
    grantAssistantContextPermission: assistant.grantAssistantContextPermission.bind(assistant),
    revokeAssistantContextPermission: assistant.revokeAssistantContextPermission.bind(assistant),
    authorizeAssistantContextAccess: assistant.authorizeAssistantContextAccess.bind(assistant),
    getAssistantDestinationProfile: assistant.getAssistantDestinationProfile.bind(assistant),
    runAssistantVocabularyLookup: assistant.runAssistantVocabularyLookup.bind(assistant),
    runAssistantVocabularySuggestion: assistant.runAssistantVocabularySuggestion.bind(assistant),
    runAssistantExternalSettingReview: assistant.runAssistantExternalSettingReview.bind(assistant),
    cancelAssistantRequest: assistant.cancelAssistantRequest.bind(assistant),
    runCanonReview: analysis.runCanonReview.bind(analysis),
    listCanonReviewCandidates: analysis.listCanonReviewCandidates.bind(analysis),
    updateCanonReviewItem: analysis.updateCanonReviewItem.bind(analysis),
    resolveCanonReviewItemTarget: analysis.resolveCanonReviewItemTarget.bind(analysis),
    decideCanonReviewItem: analysis.decideCanonReviewItem.bind(analysis),
    createContinuityThread: analysis.createContinuityThread.bind(analysis),
    updateContinuityThread: analysis.updateContinuityThread.bind(analysis),
    listContinuityThreads: analysis.listContinuityThreads.bind(analysis),
    resolveContinuityThread: analysis.resolveContinuityThread.bind(analysis),
    dismissContinuityThread: analysis.dismissContinuityThread.bind(analysis),
    runContinuityReview: analysis.runContinuityReview.bind(analysis),
    listContinuityReviewCandidates: analysis.listContinuityReviewCandidates.bind(analysis),
    updateContinuityReviewItem: analysis.updateContinuityReviewItem.bind(analysis),
    decideContinuityReviewItem: analysis.decideContinuityReviewItem.bind(analysis),
    createCharacterKnowledge: analysis.createCharacterKnowledge.bind(analysis),
    updateCharacterKnowledge: analysis.updateCharacterKnowledge.bind(analysis),
    supersedeCharacterKnowledge: analysis.supersedeCharacterKnowledge.bind(analysis),
    retireCharacterKnowledge: analysis.retireCharacterKnowledge.bind(analysis),
    listCharacterKnowledge: analysis.listCharacterKnowledge.bind(analysis),
    projectPovCharacterKnowledge: analysis.projectPovCharacterKnowledge.bind(analysis),
    listAssistantEntityContextPolicies: analysis.listAssistantEntityContextPolicies.bind(analysis),
    saveAssistantEntityContextPolicy: analysis.saveAssistantEntityContextPolicy.bind(analysis),
    planAssistantContext: analysis.planAssistantContext.bind(analysis),
    listAssistantContextManifests: analysis.listAssistantContextManifests.bind(analysis),
    listAssistantContextActivities: analysis.listAssistantContextActivities.bind(analysis),
    generateNarrativeDigest: analysis.generateNarrativeDigest.bind(analysis),
    generateSceneNarrativeDigest: analysis.generateSceneNarrativeDigest.bind(analysis),
    runAutomaticSceneAnalysis: analysis.runAutomaticSceneAnalysis.bind(analysis),
    listSceneAnalysisRuns: analysis.listSceneAnalysisRuns.bind(analysis),
    listNarrativeDigests: analysis.listNarrativeDigests.bind(analysis),
    regenerateNarrativeDigest: analysis.regenerateNarrativeDigest.bind(analysis),
    runCharacterExtraction: assistant.runCharacterExtraction.bind(assistant),
    listCharacterExtractionCandidates: assistant.listCharacterExtractionCandidates.bind(assistant),
    decideCharacterExtractionItem: assistant.decideCharacterExtractionItem.bind(assistant),
    runCharacterGeneration: assistant.runCharacterGeneration.bind(assistant),
    listCharacterGenerationCandidates: assistant.listCharacterGenerationCandidates.bind(assistant),
    decideCharacterGenerationItem: assistant.decideCharacterGenerationItem.bind(assistant),
    runSceneExtraction: assistant.runSceneExtraction.bind(assistant),
    listSceneExtractionCandidates: assistant.listSceneExtractionCandidates.bind(assistant),
    decideSceneExtractionBoundary: assistant.decideSceneExtractionBoundary.bind(assistant),
    listSceneAnnotations: scene_annotations.listSceneAnnotations.bind(scene_annotations),
    decideSceneExtractionAnnotation: assistant.decideSceneExtractionAnnotation.bind(assistant),
    runSceneDraft: assistant.runSceneDraft.bind(assistant),
    listSceneDraftCandidates: assistant.listSceneDraftCandidates.bind(assistant),
    updateSceneDraftCandidate: assistant.updateSceneDraftCandidate.bind(assistant),
    prepareSceneDraftInsertion: assistant.prepareSceneDraftInsertion.bind(assistant),
    completeSceneDraftInsertion: assistant.completeSceneDraftInsertion.bind(assistant),
    searchSceneMusicQueues: music.searchSceneMusicQueues.bind(music),
    listSceneMusicQueueCandidates: music.listSceneMusicQueueCandidates.bind(music),
    selectSceneMusicQueue: music.selectSceneMusicQueue.bind(music),
    runAssistantNotationReview: assistant.runAssistantNotationReview.bind(assistant),
    runAssistantSettingReview: assistant.runAssistantSettingReview.bind(assistant),
    getManuscriptPreflightSettings: settings.getManuscriptPreflightSettings.bind(settings),
    saveManuscriptPreflightSettings: settings.saveManuscriptPreflightSettings.bind(settings),
    prepareManuscriptTextExport: manuscript_core.prepareManuscriptTextExport.bind(manuscript_core),
    prepareCanonicalMarkdownExport: canonical_export.prepareCanonicalMarkdownExport.bind(canonical_export),
    getBackupStatus: backup.getBackupStatus.bind(backup),
    createBackupBundle: backup.createBackupBundle.bind(backup),
    restoreBackupBundle: backup.restoreBackupBundle.bind(backup),
    saveChangeBatch: manuscript_core.saveChangeBatch.bind(manuscript_core),
    saveDocumentChange: manuscript_core.saveDocumentChange.bind(manuscript_core),
    moveRangeToEpisode: manuscript_transfer.moveRangeToEpisode.bind(manuscript_transfer),
    undoMoveRangeToEpisode: manuscript_transfer.undoMoveRangeToEpisode.bind(manuscript_transfer),
    saveFormatting: manuscript_core.saveFormatting.bind(manuscript_core),
    applyManuscriptStartupRecovery: manuscript_core.applyManuscriptStartupRecovery.bind(manuscript_core),
    createDocument: workspace.createDocument.bind(workspace),
    createFirstWork: workspace.createFirstWork.bind(workspace),
    createWork: workspace.createWork.bind(workspace),
    close: infrastructure.close.bind(infrastructure),
  };
  return { facade, initialize: () => scene_geometry.initializeSceneMetadataBindings() };
}

