import { contextBridge, ipcRenderer } from "electron";

import {
  ACTIVITY_EXPORT_RECORDS_CHANNEL,
  ACTIVITY_LIST_WORK_CHANNEL,
  ACTIVITY_GET_RECORDS_GOALS_CHANNEL,
  ACTIVITY_GET_READTHROUGH_CHANNEL,
  ACTIVITY_GET_POMODORO_CHANNEL,
  ACTIVITY_CONFIGURE_START_POMODORO_CHANNEL,
  ACTIVITY_PAUSE_POMODORO_CHANNEL,
  ACTIVITY_RESUME_POMODORO_CHANNEL,
  ACTIVITY_RECONCILE_POMODORO_CHANNEL,
  ACTIVITY_STOP_POMODORO_CHANNEL,
  ACTIVITY_SAVE_RECORDS_GOALS_CHANNEL,
  ACTIVITY_SAVE_READTHROUGH_CHANNEL,
  ACTIVITY_START_FOCUS_CHANNEL,
  ACTIVITY_START_SESSION_CHANNEL,
  ACTIVITY_STOP_FOCUS_CHANNEL,
  ACTIVITY_STOP_SESSION_CHANNEL,
  ASSISTANT_CHATGPT_OAUTH_START_LOGIN_CHANNEL,
  ASSISTANT_CHATGPT_OAUTH_STATUS_CHANNEL,
  ASSISTANT_GRANT_CONTEXT_PERMISSION_CHANNEL,
  ASSISTANT_CONNECTOR_PROFILE_CHANNEL,
  ASSISTANT_DELETE_CONNECTION_CHANNEL,
  ASSISTANT_DESTINATION_PROFILE_CHANNEL,
  ASSISTANT_LIST_CONNECTIONS_CHANNEL,
  ASSISTANT_LIST_CONTEXT_STATE_CHANNEL,
  ASSISTANT_REVOKE_CONTEXT_PERMISSION_CHANNEL,
  ASSISTANT_RUN_SETTING_REVIEW_CHANNEL,
  ASSISTANT_RUN_NOTATION_REVIEW_CHANNEL,
  ASSISTANT_RUN_VOCABULARY_LOOKUP_CHANNEL,
  ASSISTANT_RUN_VOCABULARY_SUGGESTION_CHANNEL,
  ASSISTANT_RUN_EXTERNAL_SETTING_REVIEW_CHANNEL,
  ASSISTANT_SAVE_CONNECTION_CHANNEL,
  BACKUP_CREATE_CHANNEL,
  BACKUP_GET_STATUS_CHANNEL,
  BACKUP_RESTORE_CHANNEL,
  CHARACTER_CREATE_CHANNEL,
  CHARACTER_LIST_CHANNEL,
  CHARACTER_RETIRE_CHANNEL,
  CHARACTER_UPDATE_CHANNEL,
  LORE_ENTRY_ADD_EVIDENCE_CHANNEL,
  LORE_ENTRY_CREATE_CHANNEL,
  LORE_ENTRY_LIST_CHANNEL,
  LORE_ENTRY_RETIRE_CHANNEL,
  LORE_ENTRY_UPDATE_CHANNEL,
  LORE_CANDIDATE_APPROVE_CHANNEL,
  LORE_CANDIDATE_CREATE_CHANNEL,
  LORE_CANDIDATE_LIST_CHANNEL,
  LORE_CANDIDATE_REJECT_CHANNEL,
  LORE_FORESHADOW_LINK_CHANNEL,
  LORE_FORESHADOW_LIST_CHANNEL,
  LORE_FORESHADOW_UNLINK_CHANNEL,
  PUBLISHING_PARTNER_CREATE_CHANNEL,
  PUBLISHING_PARTNER_LIST_CHANNEL,
  PUBLISHING_PARTNER_UPDATE_CHANNEL,
  PUBLISHING_SUBMISSION_CREATE_CHANNEL,
  PUBLISHING_SUBMISSION_LIST_CHANNEL,
  PUBLISHING_SUBMISSION_UPDATE_CHANNEL,
  PUBLISHING_CONTRACT_CREATE_CHANNEL,
  PUBLISHING_CONTRACT_LIST_CHANNEL,
  PUBLISHING_CONTRACT_UPDATE_CHANNEL,
  PUBLISHING_PUBLICATION_CREATE_CHANNEL,
  PUBLISHING_PUBLICATION_LIST_CHANNEL,
  PUBLISHING_PUBLICATION_UPDATE_CHANNEL,
  PUBLISHING_SETTLEMENT_CREATE_CHANNEL,
  PUBLISHING_SETTLEMENT_LIST_CHANNEL,
  PUBLISHING_SETTLEMENT_UPDATE_CHANNEL,
  PUBLISHING_PAYMENT_CREATE_CHANNEL,
  PUBLISHING_PAYMENT_LIST_CHANNEL,
  PUBLISHING_PAYMENT_UPDATE_CHANNEL,
  PUBLISHING_SOURCE_CREATE_CHANNEL,
  PUBLISHING_SOURCE_LIST_CHANNEL,
  PUBLISHING_RESEARCH_PREVIEW_CHANNEL,
  PUBLISHING_RESEARCH_APPROVE_CHANNEL,
  PUBLISHING_ASSISTANT_RUN_CHANNEL,
  PUBLISHING_ASSISTANT_APPROVE_CHANNEL,
  PUBLISHING_EVIDENCE_SET_LINKS_CHANNEL,
  PUBLISHING_PARTNER_CSV_SELECT_CHANNEL,
  PUBLISHING_PARTNER_CSV_APPLY_CHANNEL,
  PUBLISHING_SUBMISSION_CSV_SELECT_CHANNEL,
  PUBLISHING_SUBMISSION_CSV_APPLY_CHANNEL,
  PUBLISHING_MAIL_CANDIDATE_LIST_CHANNEL,
  PUBLISHING_MAIL_CANDIDATE_LINK_CHANNEL,
  PUBLISHING_MAIL_CANDIDATE_UPDATE_CHANNEL,
  PUBLISHING_MAIL_CANDIDATE_REVIEW_CHANNEL,
  PUBLISHING_MAIL_CONNECTION_STATUS_CHANNEL,
  PUBLISHING_MAIL_CONNECTION_CONNECT_CHANNEL,
  PUBLISHING_MAIL_CONNECTION_SYNC_CHANNEL,
  PUBLISHING_MAIL_CONNECTION_DISCONNECT_CHANNEL,
  PUBLISHING_MAIL_SCHEDULE_STATUS_CHANNEL,
  PUBLISHING_MAIL_SCHEDULE_SAVE_CHANNEL,
  PLOT_CREATE_CHANNEL,
  PLOT_LINK_SOURCE_CHANNEL,
  PLOT_LIST_CHANNEL,
  PLOT_RETIRE_CHANNEL,
  PLOT_SOURCE_LIST_CHANNEL,
  PLOT_UPDATE_CHANNEL,
  FRAGMENT_CAPTURE_CHANNEL,
  FRAGMENT_LIST_CHANNEL,
  FRAGMENT_PROFILE_CHANNEL,
  FRAGMENT_RECORD_USE_CHANNEL,
  FRAGMENT_RETIRE_CHANNEL,
  FRAGMENT_UPDATE_CHANNEL,
  FORESHADOW_CREATE_LINE_CHANNEL,
  FORESHADOW_CREATE_POINT_CHANNEL,
  FORESHADOW_LIST_LINES_CHANNEL,
  FORESHADOW_LIST_POINTS_CHANNEL,
  FORESHADOW_POINT_PROFILE_CHANNEL,
  FORESHADOW_RETIRE_LINE_CHANNEL,
  FORESHADOW_UPDATE_LINE_CHANNEL,
  type BridgeListen,
  createStudioBridge,
  MANUSCRIPT_APPLY_STARTUP_RECOVERY_CHANNEL,
  MANUSCRIPT_CLOSE_REQUEST_CHANNEL,
  MANUSCRIPT_COMPLETE_CLOSE_REQUEST_CHANNEL,
  MANUSCRIPT_DOCUMENT_PROFILE_CHANNEL,
  MANUSCRIPT_GET_CONTINUOUS_READING_PROGRESS_CHANNEL,
  MANUSCRIPT_FORMATTING_PROFILE_CHANNEL,
  MANUSCRIPT_EXPORT_TEXT_CHANNEL,
  MANUSCRIPT_INPUT_PROFILE_CHANNEL,
  MANUSCRIPT_PREFLIGHT_GET_SETTINGS_CHANNEL,
  MANUSCRIPT_PREFLIGHT_PROFILE_CHANNEL,
  MANUSCRIPT_PREFLIGHT_SAVE_SETTINGS_CHANNEL,
  MANUSCRIPT_PERSISTENCE_PROFILE_CHANNEL,
  MANUSCRIPT_RESUME_CHECKPOINT_CHANNEL,
  MANUSCRIPT_SAVE_CONTINUOUS_READING_PROGRESS_CHANNEL,
  MANUSCRIPT_SAVE_CHANGE_BATCH_CHANNEL,
  MANUSCRIPT_SAVE_DOCUMENT_CHANGE_CHANNEL,
  MANUSCRIPT_SAVE_FORMATTING_CHANNEL,
  MANUSCRIPT_STARTUP_RECOVERY_CHANNEL,
  MIGRATION_RUN_LEGACY_REHEARSAL_CHANNEL,
  RUNTIME_INFO_CHANNEL,
  QUICK_TOOLS_GET_MEMO_CHANNEL,
  QUICK_TOOLS_SAVE_MEMO_CHANNEL,
  APP_SETTINGS_PROFILE_CHANNEL,
  APP_SETTINGS_GET_CHANNEL,
  APP_SETTINGS_SAVE_CHANNEL,
  MUSIC_SETTINGS_PROFILE_CHANNEL,
  MUSIC_SETTINGS_GET_WORK_CHANNEL,
  MUSIC_SETTINGS_SAVE_WORK_CHANNEL,
  YOUTUBE_MUSIC_CONNECTION_STATUS_CHANNEL,
  YOUTUBE_MUSIC_CONNECTION_SAVE_CHANNEL,
  SCHEDULE_CREATE_ITEM_CHANNEL,
  SCHEDULE_LIST_WORK_CHANNEL,
  SCHEDULE_RETIRE_ITEM_CHANNEL,
  SCHEDULE_SET_COMPLETION_CHANNEL,
  SCHEDULE_UPDATE_ITEM_CHANNEL,
  STRUCTURE_CREATE_EVENT_BLOCK_CHANNEL,
  STRUCTURE_CREATE_SCENE_OVERRIDE_CHANNEL,
  STRUCTURE_LIST_EVENT_BLOCKS_CHANNEL,
  STRUCTURE_LIST_SCENE_OVERRIDES_CHANNEL,
  VERSION_CREATE_WORK_SNAPSHOT_CHANNEL,
  VERSION_COMPARE_WORK_SNAPSHOT_CHANNEL,
  VERSION_LIST_DOCUMENT_REVISIONS_CHANNEL,
  VERSION_LIST_WORK_SNAPSHOTS_CHANNEL,
  VERSION_RESTORE_DOCUMENT_REVISION_CHANNEL,
  WORKSPACE_ACTIVATE_LOCATION_CHANNEL,
  WORKSPACE_CATALOG_CHANNEL,
  WORKSPACE_FAVORITES_CHANNEL,
  WORKSPACE_SET_FAVORITE_CHANNEL,
  WORKSPACE_COVERS_CHANNEL,
  WORKSPACE_SELECT_COVER_CHANNEL,
  WORKSPACE_CAPTURE_RESUME_CHANNEL,
  WORKSPACE_CREATE_DOCUMENT_CHANNEL,
  WORKSPACE_CREATE_DOCUMENT_FOLDER_CHANNEL,
  WORKSPACE_CREATE_FIRST_WORK_CHANNEL,
  WORKSPACE_CREATE_WORK_CHANNEL,
  WORKSPACE_MOVE_DOCUMENT_CHANNEL,
  WORKSPACE_PLACE_DOCUMENT_IN_FOLDER_CHANNEL,
  WORKSPACE_RENAME_DOCUMENT_FOLDER_CHANNEL,
  WORKSPACE_RENAME_DOCUMENT_CHANNEL,
  WORKSPACE_RENAME_WORK_CHANNEL,
  WORKSPACE_RETIRE_DOCUMENT_CHANNEL,
  WORKSPACE_RETIRE_DOCUMENT_FOLDER_CHANNEL,
  WORKSPACE_RETIRE_WORK_CHANNEL,
} from "../application/contracts/studio-bridge";

const manuscriptCloseRequestListeners = new Set<
  Parameters<BridgeListen>[1]
>();
let pendingManuscriptCloseRequest: unknown;
let hasPendingManuscriptCloseRequest = false;

ipcRenderer.on(
  MANUSCRIPT_CLOSE_REQUEST_CHANNEL,
  (
    _event: Electron.IpcRendererEvent,
    payload: unknown,
  ) => {
    if (
      manuscriptCloseRequestListeners.size === 0
    ) {
      pendingManuscriptCloseRequest = payload;
      hasPendingManuscriptCloseRequest = true;
      return;
    }
    for (const listener of manuscriptCloseRequestListeners) {
      listener(payload);
    }
  },
);

const studioBridge = createStudioBridge(
  (channel, payload) => {
    if (
      channel !== RUNTIME_INFO_CHANNEL &&
      channel !== MANUSCRIPT_INPUT_PROFILE_CHANNEL &&
      channel !== MANUSCRIPT_DOCUMENT_PROFILE_CHANNEL &&
      channel !== MANUSCRIPT_GET_CONTINUOUS_READING_PROGRESS_CHANNEL &&
      channel !== MANUSCRIPT_FORMATTING_PROFILE_CHANNEL &&
      channel !== MANUSCRIPT_PREFLIGHT_PROFILE_CHANNEL &&
      channel !== MANUSCRIPT_PREFLIGHT_GET_SETTINGS_CHANNEL &&
      channel !== MANUSCRIPT_PREFLIGHT_SAVE_SETTINGS_CHANNEL &&
      channel !== FRAGMENT_PROFILE_CHANNEL &&
      channel !== FRAGMENT_CAPTURE_CHANNEL &&
      channel !== FRAGMENT_LIST_CHANNEL &&
      channel !== FRAGMENT_UPDATE_CHANNEL &&
      channel !== FRAGMENT_RECORD_USE_CHANNEL &&
      channel !== FRAGMENT_RETIRE_CHANNEL &&
      channel !== CHARACTER_CREATE_CHANNEL &&
      channel !== CHARACTER_LIST_CHANNEL &&
      channel !== CHARACTER_UPDATE_CHANNEL &&
      channel !== CHARACTER_RETIRE_CHANNEL &&
      channel !== LORE_ENTRY_CREATE_CHANNEL &&
      channel !== LORE_ENTRY_LIST_CHANNEL &&
      channel !== LORE_ENTRY_UPDATE_CHANNEL &&
      channel !== LORE_ENTRY_ADD_EVIDENCE_CHANNEL &&
      channel !== LORE_ENTRY_RETIRE_CHANNEL &&
      channel !== LORE_CANDIDATE_CREATE_CHANNEL &&
      channel !== LORE_CANDIDATE_LIST_CHANNEL &&
      channel !== LORE_CANDIDATE_APPROVE_CHANNEL &&
      channel !== LORE_CANDIDATE_REJECT_CHANNEL &&
      channel !== LORE_FORESHADOW_LINK_CHANNEL &&
      channel !== LORE_FORESHADOW_LIST_CHANNEL &&
      channel !== LORE_FORESHADOW_UNLINK_CHANNEL &&
      channel !== PUBLISHING_PARTNER_CREATE_CHANNEL &&
      channel !== PUBLISHING_PARTNER_LIST_CHANNEL &&
      channel !== PUBLISHING_PARTNER_UPDATE_CHANNEL &&
      channel !== PUBLISHING_SUBMISSION_CREATE_CHANNEL &&
      channel !== PUBLISHING_SUBMISSION_LIST_CHANNEL &&
      channel !== PUBLISHING_SUBMISSION_UPDATE_CHANNEL &&
      channel !== PUBLISHING_CONTRACT_CREATE_CHANNEL &&
      channel !== PUBLISHING_CONTRACT_LIST_CHANNEL &&
      channel !== PUBLISHING_CONTRACT_UPDATE_CHANNEL &&
      channel !== PUBLISHING_PUBLICATION_CREATE_CHANNEL &&
      channel !== PUBLISHING_PUBLICATION_LIST_CHANNEL &&
      channel !== PUBLISHING_PUBLICATION_UPDATE_CHANNEL &&
      channel !== PUBLISHING_SETTLEMENT_CREATE_CHANNEL &&
      channel !== PUBLISHING_SETTLEMENT_LIST_CHANNEL &&
      channel !== PUBLISHING_SETTLEMENT_UPDATE_CHANNEL &&
      channel !== PUBLISHING_PAYMENT_CREATE_CHANNEL &&
      channel !== PUBLISHING_PAYMENT_LIST_CHANNEL &&
      channel !== PUBLISHING_PAYMENT_UPDATE_CHANNEL &&
      channel !== PUBLISHING_SOURCE_CREATE_CHANNEL &&
      channel !== PUBLISHING_SOURCE_LIST_CHANNEL &&
      channel !== PUBLISHING_RESEARCH_PREVIEW_CHANNEL &&
      channel !== PUBLISHING_RESEARCH_APPROVE_CHANNEL &&
      channel !== PUBLISHING_ASSISTANT_RUN_CHANNEL &&
      channel !== PUBLISHING_ASSISTANT_APPROVE_CHANNEL &&
      channel !== PUBLISHING_EVIDENCE_SET_LINKS_CHANNEL &&
      channel !== PUBLISHING_PARTNER_CSV_SELECT_CHANNEL &&
      channel !== PUBLISHING_PARTNER_CSV_APPLY_CHANNEL &&
      channel !== PUBLISHING_SUBMISSION_CSV_SELECT_CHANNEL &&
      channel !== PUBLISHING_SUBMISSION_CSV_APPLY_CHANNEL &&
      channel !== PUBLISHING_MAIL_CANDIDATE_LIST_CHANNEL &&
      channel !== PUBLISHING_MAIL_CANDIDATE_LINK_CHANNEL &&
      channel !== PUBLISHING_MAIL_CANDIDATE_UPDATE_CHANNEL &&
      channel !== PUBLISHING_MAIL_CANDIDATE_REVIEW_CHANNEL &&
      channel !== PUBLISHING_MAIL_CONNECTION_STATUS_CHANNEL &&
      channel !== PUBLISHING_MAIL_CONNECTION_CONNECT_CHANNEL &&
      channel !== PUBLISHING_MAIL_CONNECTION_SYNC_CHANNEL &&
      channel !== PUBLISHING_MAIL_CONNECTION_DISCONNECT_CHANNEL &&
      channel !== PUBLISHING_MAIL_SCHEDULE_STATUS_CHANNEL &&
      channel !== PUBLISHING_MAIL_SCHEDULE_SAVE_CHANNEL &&
      channel !== PLOT_CREATE_CHANNEL &&
      channel !== PLOT_LIST_CHANNEL &&
      channel !== PLOT_UPDATE_CHANNEL &&
      channel !== PLOT_RETIRE_CHANNEL &&
      channel !== PLOT_LINK_SOURCE_CHANNEL &&
      channel !== PLOT_SOURCE_LIST_CHANNEL &&
      channel !== FORESHADOW_CREATE_LINE_CHANNEL &&
      channel !== FORESHADOW_LIST_LINES_CHANNEL &&
      channel !== FORESHADOW_UPDATE_LINE_CHANNEL &&
      channel !== FORESHADOW_RETIRE_LINE_CHANNEL &&
      channel !== FORESHADOW_POINT_PROFILE_CHANNEL &&
      channel !== FORESHADOW_CREATE_POINT_CHANNEL &&
      channel !== FORESHADOW_LIST_POINTS_CHANNEL &&
      channel !== MANUSCRIPT_EXPORT_TEXT_CHANNEL &&
      channel !== MANUSCRIPT_PERSISTENCE_PROFILE_CHANNEL &&
      channel !== MANUSCRIPT_RESUME_CHECKPOINT_CHANNEL &&
      channel !== MANUSCRIPT_SAVE_CONTINUOUS_READING_PROGRESS_CHANNEL &&
      channel !== MANUSCRIPT_SAVE_CHANGE_BATCH_CHANNEL &&
      channel !== MANUSCRIPT_SAVE_DOCUMENT_CHANGE_CHANNEL &&
      channel !== MANUSCRIPT_SAVE_FORMATTING_CHANNEL &&
      channel !== MANUSCRIPT_STARTUP_RECOVERY_CHANNEL &&
      channel !==
        MANUSCRIPT_APPLY_STARTUP_RECOVERY_CHANNEL &&
      channel !==
        MANUSCRIPT_COMPLETE_CLOSE_REQUEST_CHANNEL &&
      channel !== WORKSPACE_CATALOG_CHANNEL &&
      channel !== WORKSPACE_FAVORITES_CHANNEL &&
      channel !== WORKSPACE_SET_FAVORITE_CHANNEL &&
      channel !== WORKSPACE_COVERS_CHANNEL &&
      channel !== WORKSPACE_SELECT_COVER_CHANNEL &&
      channel !== WORKSPACE_CREATE_FIRST_WORK_CHANNEL &&
      channel !== WORKSPACE_CREATE_WORK_CHANNEL &&
      channel !== WORKSPACE_CREATE_DOCUMENT_CHANNEL &&
      channel !== WORKSPACE_CREATE_DOCUMENT_FOLDER_CHANNEL &&
      channel !== WORKSPACE_MOVE_DOCUMENT_CHANNEL &&
      channel !== WORKSPACE_PLACE_DOCUMENT_IN_FOLDER_CHANNEL &&
      channel !== WORKSPACE_RENAME_DOCUMENT_FOLDER_CHANNEL &&
      channel !== WORKSPACE_RENAME_WORK_CHANNEL &&
      channel !== WORKSPACE_RENAME_DOCUMENT_CHANNEL &&
      channel !== WORKSPACE_RETIRE_WORK_CHANNEL &&
      channel !== WORKSPACE_RETIRE_DOCUMENT_CHANNEL &&
      channel !== WORKSPACE_RETIRE_DOCUMENT_FOLDER_CHANNEL &&
      channel !== WORKSPACE_ACTIVATE_LOCATION_CHANNEL &&
      channel !== WORKSPACE_CAPTURE_RESUME_CHANNEL &&
      channel !== STRUCTURE_CREATE_EVENT_BLOCK_CHANNEL &&
      channel !== STRUCTURE_LIST_EVENT_BLOCKS_CHANNEL &&
      channel !== STRUCTURE_CREATE_SCENE_OVERRIDE_CHANNEL &&
      channel !== STRUCTURE_LIST_SCENE_OVERRIDES_CHANNEL &&
      channel !== ACTIVITY_EXPORT_RECORDS_CHANNEL &&
      channel !== ACTIVITY_LIST_WORK_CHANNEL &&
      channel !== ACTIVITY_GET_RECORDS_GOALS_CHANNEL &&
      channel !== ACTIVITY_SAVE_RECORDS_GOALS_CHANNEL &&
      channel !== ACTIVITY_GET_READTHROUGH_CHANNEL &&
      channel !== ACTIVITY_SAVE_READTHROUGH_CHANNEL &&
      channel !== ACTIVITY_START_SESSION_CHANNEL &&
      channel !== ACTIVITY_STOP_SESSION_CHANNEL &&
      channel !== ACTIVITY_START_FOCUS_CHANNEL &&
      channel !== ACTIVITY_STOP_FOCUS_CHANNEL &&
      channel !== ACTIVITY_GET_POMODORO_CHANNEL &&
      channel !== ACTIVITY_CONFIGURE_START_POMODORO_CHANNEL &&
      channel !== ACTIVITY_PAUSE_POMODORO_CHANNEL &&
      channel !== ACTIVITY_RESUME_POMODORO_CHANNEL &&
      channel !== ACTIVITY_RECONCILE_POMODORO_CHANNEL &&
      channel !== ACTIVITY_STOP_POMODORO_CHANNEL &&
      channel !== SCHEDULE_LIST_WORK_CHANNEL &&
      channel !== SCHEDULE_CREATE_ITEM_CHANNEL &&
      channel !== SCHEDULE_UPDATE_ITEM_CHANNEL &&
      channel !== SCHEDULE_RETIRE_ITEM_CHANNEL &&
      channel !== SCHEDULE_SET_COMPLETION_CHANNEL &&
      channel !== QUICK_TOOLS_GET_MEMO_CHANNEL &&
      channel !== QUICK_TOOLS_SAVE_MEMO_CHANNEL &&
      channel !== ASSISTANT_CHATGPT_OAUTH_STATUS_CHANNEL &&
      channel !== ASSISTANT_CHATGPT_OAUTH_START_LOGIN_CHANNEL &&
      channel !== ASSISTANT_LIST_CONTEXT_STATE_CHANNEL &&
      channel !== ASSISTANT_LIST_CONNECTIONS_CHANNEL &&
      channel !== ASSISTANT_SAVE_CONNECTION_CHANNEL &&
      channel !== ASSISTANT_DELETE_CONNECTION_CHANNEL &&
      channel !== ASSISTANT_GRANT_CONTEXT_PERMISSION_CHANNEL &&
      channel !== ASSISTANT_REVOKE_CONTEXT_PERMISSION_CHANNEL &&
      channel !== ASSISTANT_CONNECTOR_PROFILE_CHANNEL &&
      channel !== ASSISTANT_DESTINATION_PROFILE_CHANNEL &&
      channel !== ASSISTANT_RUN_VOCABULARY_LOOKUP_CHANNEL &&
      channel !== ASSISTANT_RUN_VOCABULARY_SUGGESTION_CHANNEL &&
      channel !== ASSISTANT_RUN_EXTERNAL_SETTING_REVIEW_CHANNEL &&
      channel !== ASSISTANT_RUN_NOTATION_REVIEW_CHANNEL &&
      channel !== ASSISTANT_RUN_SETTING_REVIEW_CHANNEL &&
      channel !== APP_SETTINGS_PROFILE_CHANNEL &&
      channel !== APP_SETTINGS_GET_CHANNEL &&
      channel !== APP_SETTINGS_SAVE_CHANNEL &&
      channel !== MUSIC_SETTINGS_PROFILE_CHANNEL &&
      channel !== MUSIC_SETTINGS_GET_WORK_CHANNEL &&
      channel !== MUSIC_SETTINGS_SAVE_WORK_CHANNEL &&
      channel !== YOUTUBE_MUSIC_CONNECTION_STATUS_CHANNEL &&
      channel !== YOUTUBE_MUSIC_CONNECTION_SAVE_CHANNEL &&
      channel !== VERSION_LIST_DOCUMENT_REVISIONS_CHANNEL &&
      channel !== VERSION_RESTORE_DOCUMENT_REVISION_CHANNEL &&
      channel !== VERSION_CREATE_WORK_SNAPSHOT_CHANNEL &&
      channel !== VERSION_LIST_WORK_SNAPSHOTS_CHANNEL &&
      channel !== VERSION_COMPARE_WORK_SNAPSHOT_CHANNEL &&
      channel !== BACKUP_GET_STATUS_CHANNEL &&
      channel !== BACKUP_CREATE_CHANNEL &&
      channel !== BACKUP_RESTORE_CHANNEL &&
      channel !== MIGRATION_RUN_LEGACY_REHEARSAL_CHANNEL
    ) {
      return Promise.reject(
        new Error(
          "Unsupported bridge channel",
        ),
      );
    }
    return payload === undefined
      ? ipcRenderer.invoke(channel)
      : ipcRenderer.invoke(
          channel,
          payload,
        );
  },
  (channel, listener) => {
    if (
      channel !==
      MANUSCRIPT_CLOSE_REQUEST_CHANNEL
    ) {
      throw new Error(
        "Unsupported bridge event channel",
      );
    }
    manuscriptCloseRequestListeners.add(listener);
    if (hasPendingManuscriptCloseRequest) {
      const payload =
        pendingManuscriptCloseRequest;
      pendingManuscriptCloseRequest =
        undefined;
      hasPendingManuscriptCloseRequest = false;
      listener(payload);
    }
    return () => {
      manuscriptCloseRequestListeners.delete(
        listener,
      );
    };
  },
);

contextBridge.exposeInMainWorld("eumStudio", studioBridge);
