import {
  MANUSCRIPT_APPLY_STARTUP_RECOVERY_CHANNEL,
  MANUSCRIPT_COMPLETE_CLOSE_REQUEST_CHANNEL,
  MANUSCRIPT_DOCUMENT_PROFILE_CHANNEL,
  MANUSCRIPT_EXPORT_TEXT_CHANNEL,
  MANUSCRIPT_FORMATTING_PROFILE_CHANNEL,
  MANUSCRIPT_GET_CONTINUOUS_READING_PROGRESS_CHANNEL,
  MANUSCRIPT_GET_WORK_LAYOUT_SETTINGS_CHANNEL,
  MANUSCRIPT_INPUT_PROFILE_CHANNEL,
  MANUSCRIPT_MOVE_RANGE_TO_EPISODE_CHANNEL,
  MANUSCRIPT_PERSISTENCE_PROFILE_CHANNEL,
  MANUSCRIPT_PREFLIGHT_GET_SETTINGS_CHANNEL,
  MANUSCRIPT_PREFLIGHT_PROFILE_CHANNEL,
  MANUSCRIPT_PREFLIGHT_SAVE_SETTINGS_CHANNEL,
  MANUSCRIPT_RESUME_CHECKPOINT_CHANNEL,
  MANUSCRIPT_SAVE_CHANGE_BATCH_CHANNEL,
  MANUSCRIPT_SAVE_CONTINUOUS_READING_PROGRESS_CHANNEL,
  MANUSCRIPT_SAVE_DOCUMENT_CHANGE_CHANNEL,
  MANUSCRIPT_SAVE_FORMATTING_CHANNEL,
  MANUSCRIPT_SAVE_WORK_LAYOUT_SETTINGS_CHANNEL,
  MANUSCRIPT_SELECT_TEXT_IMPORT_CHANNEL,
  MANUSCRIPT_STARTUP_RECOVERY_CHANNEL,
  MANUSCRIPT_UNDO_MOVE_RANGE_TO_EPISODE_CHANNEL,
  createEditorBridge,
  type BridgeListen,
  type EditorBridge,
  type EditorBridgePayload,
} from "./bridge/editor-bridge";
export * from "./bridge/editor-bridge";
import {
  WORKSPACE_ACTIVATE_LOCATION_CHANNEL,
  WORKSPACE_CAPTURE_RESUME_CHANNEL,
  WORKSPACE_CATALOG_CHANNEL,
  WORKSPACE_CLEAR_DOCUMENT_COMPLETION_CHANNEL,
  WORKSPACE_COMPLETE_DOCUMENT_CHANNEL,
  WORKSPACE_COVERS_CHANNEL,
  WORKSPACE_CREATE_DOCUMENT_CHANNEL,
  WORKSPACE_CREATE_DOCUMENT_FOLDER_CHANNEL,
  WORKSPACE_CREATE_FIRST_WORK_CHANNEL,
  WORKSPACE_CREATE_WORK_CHANNEL,
  WORKSPACE_FAVORITES_CHANNEL,
  WORKSPACE_GET_DOCUMENT_COMPLETION_CHANNEL,
  WORKSPACE_MOVE_DOCUMENT_CHANNEL,
  WORKSPACE_PLACE_DOCUMENT_IN_FOLDER_CHANNEL,
  WORKSPACE_RENAME_DOCUMENT_CHANNEL,
  WORKSPACE_RENAME_DOCUMENT_FOLDER_CHANNEL,
  WORKSPACE_RENAME_WORK_CHANNEL,
  WORKSPACE_RETIRE_DOCUMENT_CHANNEL,
  WORKSPACE_RETIRE_ALL_DOCUMENTS_CHANNEL,
  WORKSPACE_RETIRE_DOCUMENT_FOLDER_CHANNEL,
  WORKSPACE_RETIRE_WORK_CHANNEL,
  WORKSPACE_SELECT_COVER_CHANNEL,
  WORKSPACE_SET_FAVORITE_CHANNEL,
  createWorkspaceBridge,
  type WorkspaceBridge,
  type WorkspaceBridgePayload,
} from "./bridge/workspace-bridge";
export * from "./bridge/workspace-bridge";
import {
  RUNTIME_INFO_CHANNEL,
  createSystemBridge,
  type SystemBridge,
} from "./bridge/system-bridge";
export * from "./bridge/system-bridge";
import {
  STRUCTURE_COMPLETE_SCENE_DRAFT_INSERTION_CHANNEL,
  STRUCTURE_CREATE_ANCHORLESS_EVENT_CHANNEL,
  STRUCTURE_CREATE_EVENT_BLOCK_CHANNEL,
  STRUCTURE_CREATE_SCENE_OVERRIDE_CHANNEL,
  STRUCTURE_RELOCATE_SCENE_SEGMENT_CHANNEL,
  STRUCTURE_DECIDE_SCENE_EXTRACTION_ANNOTATION_CHANNEL,
  STRUCTURE_DECIDE_SCENE_EXTRACTION_BOUNDARY_CHANNEL,
  STRUCTURE_LINK_EVENT_SOURCE_CHANNEL,
  STRUCTURE_LIST_EVENT_BLOCKS_CHANNEL,
  STRUCTURE_LIST_EVENT_RAIL_CHANNEL,
  STRUCTURE_LIST_SCENE_ANNOTATIONS_CHANNEL,
  STRUCTURE_LIST_SCENE_DRAFT_CANDIDATES_CHANNEL,
  STRUCTURE_LIST_SCENE_EXTRACTION_CANDIDATES_CHANNEL,
  STRUCTURE_LIST_SCENE_OVERRIDES_CHANNEL,
  STRUCTURE_LIST_SCENE_PROJECTION_CHANNEL,
  STRUCTURE_MOVE_EVENT_BLOCK_CHANNEL,
  STRUCTURE_PREPARE_SCENE_DRAFT_INSERTION_CHANNEL,
  STRUCTURE_REPLACE_EVENT_SOURCE_CHANNEL,
  STRUCTURE_RETIRE_EVENT_SOURCE_CHANNEL,
  STRUCTURE_RUN_SCENE_DRAFT_CHANNEL,
  STRUCTURE_RUN_SCENE_EXTRACTION_CHANNEL,
  STRUCTURE_SET_SCENE_EVENT_OVERRIDE_CHANNEL,
  STRUCTURE_UPDATE_SCENE_DRAFT_CANDIDATE_CHANNEL,
  STRUCTURE_UPDATE_SCENE_RULE_SET_CHANNEL,
  createStructureBridge,
  type StructureBridge,
  type StructureBridgePayload,
} from "./bridge/structure-bridge";
export * from "./bridge/structure-bridge";
import {
  createFragmentsBridge,
  FRAGMENT_CAPTURE_CHANNEL,
  FRAGMENT_LIST_CHANNEL,
  FRAGMENT_PROFILE_CHANNEL,
  FRAGMENT_RECORD_USE_CHANNEL,
  FRAGMENT_RETIRE_CHANNEL,
  FRAGMENT_UPDATE_CHANNEL,
  type FragmentBridgePayload,
  type FragmentsBridge,
} from "./bridge/fragments-bridge";
export {
  createFragmentsBridge,
  FRAGMENT_CAPTURE_CHANNEL,
  FRAGMENT_LIST_CHANNEL,
  FRAGMENT_PROFILE_CHANNEL,
  FRAGMENT_RECORD_USE_CHANNEL,
  FRAGMENT_RETIRE_CHANNEL,
  FRAGMENT_UPDATE_CHANNEL,
  type FragmentBridgeChannel,
  type FragmentBridgeInvoke,
  type FragmentBridgePayload,
  type FragmentsBridge,
} from "./bridge/fragments-bridge";
import {
  createForeshadowingBridge,
  FORESHADOW_CREATE_LINE_CHANNEL,
  FORESHADOW_CREATE_POINT_CHANNEL,
  FORESHADOW_LIST_LINES_CHANNEL,
  FORESHADOW_LIST_POINTS_CHANNEL,
  FORESHADOW_POINT_PROFILE_CHANNEL,
  FORESHADOW_RETIRE_LINE_CHANNEL,
  FORESHADOW_UPDATE_LINE_CHANNEL,
  type ForeshadowingBridge,
  type ForeshadowingBridgePayload,
} from "./bridge/foreshadowing-bridge";
export {
  createForeshadowingBridge,
  FORESHADOW_CREATE_LINE_CHANNEL,
  FORESHADOW_CREATE_POINT_CHANNEL,
  FORESHADOW_LIST_LINES_CHANNEL,
  FORESHADOW_LIST_POINTS_CHANNEL,
  FORESHADOW_POINT_PROFILE_CHANNEL,
  FORESHADOW_RETIRE_LINE_CHANNEL,
  FORESHADOW_UPDATE_LINE_CHANNEL,
  type ForeshadowingBridge,
  type ForeshadowingBridgeChannel,
  type ForeshadowingBridgeInvoke,
  type ForeshadowingBridgePayload,
} from "./bridge/foreshadowing-bridge";
import {
  createCharactersBridge,
  CHARACTER_ADD_EVIDENCE_CHANNEL,
  CHARACTER_CREATE_CHANNEL,
  CHARACTER_EXTRACTION_DECIDE_CHANNEL,
  CHARACTER_EXTRACTION_LIST_CHANNEL,
  CHARACTER_EXTRACTION_RUN_CHANNEL,
  CHARACTER_GENERATION_DECIDE_CHANNEL,
  CHARACTER_GENERATION_LIST_CHANNEL,
  CHARACTER_GENERATION_RUN_CHANNEL,
  CHARACTER_LIST_CHANNEL,
  CHARACTER_RELATION_CREATE_CHANNEL,
  CHARACTER_RELATION_LIST_CHANNEL,
  CHARACTER_RELATION_RETIRE_CHANNEL,
  CHARACTER_RELATION_UPDATE_CHANNEL,
  CHARACTER_RETIRE_CHANNEL,
  CHARACTER_UPDATE_CHANNEL,
  type CharactersBridge,
  type CharactersBridgePayload,
} from "./bridge/characters-bridge";
export * from "./bridge/characters-bridge";
import {
  createLoreBridge,
  LORE_CANDIDATE_APPROVE_CHANNEL,
  LORE_CANDIDATE_CREATE_CHANNEL,
  LORE_CANDIDATE_LIST_CHANNEL,
  LORE_CANDIDATE_REJECT_CHANNEL,
  LORE_ENTRY_ADD_EVIDENCE_CHANNEL,
  LORE_ENTRY_CREATE_CHANNEL,
  LORE_ENTRY_LIST_CHANNEL,
  LORE_ENTRY_RETIRE_CHANNEL,
  LORE_ENTRY_UPDATE_CHANNEL,
  LORE_FORESHADOW_LINK_CHANNEL,
  LORE_FORESHADOW_LIST_CHANNEL,
  LORE_FORESHADOW_UNLINK_CHANNEL,
  type LoreBridge,
  type LoreBridgePayload,
  type LoreCandidatesBridge,
  type LoreEntriesBridge,
  type LoreForeshadowLinksBridge,
} from "./bridge/lore-bridge";
export * from "./bridge/lore-bridge";
import {
  createPublishingBridge,
  PUBLISHING_ASSISTANT_APPROVE_CHANNEL,
  PUBLISHING_ASSISTANT_RUN_CHANNEL,
  PUBLISHING_CONTRACT_CREATE_CHANNEL,
  PUBLISHING_CONTRACT_LIST_CHANNEL,
  PUBLISHING_CONTRACT_UPDATE_CHANNEL,
  PUBLISHING_EVIDENCE_SET_LINKS_CHANNEL,
  PUBLISHING_MAIL_CANDIDATE_LINK_CHANNEL,
  PUBLISHING_MAIL_CANDIDATE_LIST_CHANNEL,
  PUBLISHING_MAIL_CANDIDATE_REVIEW_CHANNEL,
  PUBLISHING_MAIL_CANDIDATE_UPDATE_CHANNEL,
  PUBLISHING_MAIL_CONNECTION_CONNECT_CHANNEL,
  PUBLISHING_MAIL_CONNECTION_DISCONNECT_CHANNEL,
  PUBLISHING_MAIL_CONNECTION_STATUS_CHANNEL,
  PUBLISHING_MAIL_CONNECTION_SYNC_CHANNEL,
  PUBLISHING_MAIL_SCHEDULE_SAVE_CHANNEL,
  PUBLISHING_MAIL_SCHEDULE_STATUS_CHANNEL,
  PUBLISHING_PARTNER_CREATE_CHANNEL,
  PUBLISHING_PARTNER_CSV_APPLY_CHANNEL,
  PUBLISHING_PARTNER_CSV_SELECT_CHANNEL,
  PUBLISHING_PARTNER_LIST_CHANNEL,
  PUBLISHING_PARTNER_UPDATE_CHANNEL,
  PUBLISHING_PAYMENT_CREATE_CHANNEL,
  PUBLISHING_PAYMENT_LIST_CHANNEL,
  PUBLISHING_PAYMENT_UPDATE_CHANNEL,
  PUBLISHING_PUBLICATION_CREATE_CHANNEL,
  PUBLISHING_PUBLICATION_LIST_CHANNEL,
  PUBLISHING_PUBLICATION_UPDATE_CHANNEL,
  PUBLISHING_RESEARCH_APPROVE_CHANNEL,
  PUBLISHING_RESEARCH_PREVIEW_CHANNEL,
  PUBLISHING_SETTLEMENT_CREATE_CHANNEL,
  PUBLISHING_SETTLEMENT_LIST_CHANNEL,
  PUBLISHING_SETTLEMENT_UPDATE_CHANNEL,
  PUBLISHING_SOURCE_CREATE_CHANNEL,
  PUBLISHING_SOURCE_LIST_CHANNEL,
  PUBLISHING_SUBMISSION_CREATE_CHANNEL,
  PUBLISHING_SUBMISSION_CSV_APPLY_CHANNEL,
  PUBLISHING_SUBMISSION_CSV_SELECT_CHANNEL,
  PUBLISHING_SUBMISSION_LIST_CHANNEL,
  PUBLISHING_SUBMISSION_UPDATE_CHANNEL,
  type PublishingBridge,
  type PublishingBridgePayload,
} from "./bridge/publishing-bridge";
export * from "./bridge/publishing-bridge";
import {
  PLOT_CREATE_CHANNEL,
  PLOT_CREATE_EVENT_CHANNEL,
  PLOT_CREATE_FROM_EVENT_CHANNEL,
  PLOT_DEFAULT_BOARD_CHANNEL,
  PLOT_EVENT_LINK_LIST_CHANNEL,
  PLOT_LINK_EVENT_CHANNEL,
  PLOT_LINK_SOURCE_CHANNEL,
  PLOT_LIST_CHANNEL,
  PLOT_MOVE_PLACEMENT_CHANNEL,
  PLOT_RETIRE_CHANNEL,
  PLOT_SET_STORY_TIME_CHANNEL,
  PLOT_SOURCE_LIST_CHANNEL,
  PLOT_UNLINK_EVENT_CHANNEL,
  PLOT_UPDATE_CHANNEL,
  createPlotsBridge,
  type PlotsBridge,
  type PlotsBridgePayload,
} from "./bridge/plots-bridge";
export * from "./bridge/plots-bridge";
import {
  createActivityBridge,
  ACTIVITY_CONFIGURE_START_POMODORO_CHANNEL,
  ACTIVITY_EXPORT_RECORDS_CHANNEL,
  ACTIVITY_GET_POMODORO_CHANNEL,
  ACTIVITY_GET_READTHROUGH_CHANNEL,
  ACTIVITY_GET_RECORDS_GOALS_CHANNEL,
  ACTIVITY_LIST_WORK_CHANNEL,
  ACTIVITY_PAUSE_POMODORO_CHANNEL,
  ACTIVITY_RECONCILE_POMODORO_CHANNEL,
  ACTIVITY_RESUME_POMODORO_CHANNEL,
  ACTIVITY_SAVE_READTHROUGH_CHANNEL,
  ACTIVITY_SAVE_RECORDS_GOALS_CHANNEL,
  ACTIVITY_START_FOCUS_CHANNEL,
  ACTIVITY_START_SESSION_CHANNEL,
  ACTIVITY_STOP_FOCUS_CHANNEL,
  ACTIVITY_STOP_POMODORO_CHANNEL,
  ACTIVITY_STOP_SESSION_CHANNEL,
  ACTIVITY_UPDATE_POMODORO_NOTE_CHANNEL,
  type ActivityBridge,
  type ActivityBridgePayload,
} from "./bridge/activity-bridge";
export * from "./bridge/activity-bridge";
import {
  createScheduleBridge,
  SCHEDULE_CREATE_ITEM_CHANNEL,
  SCHEDULE_LIST_CALENDAR_CHANNEL,
  SCHEDULE_LIST_TODAY_CHANNEL,
  SCHEDULE_LIST_WORK_CHANNEL,
  SCHEDULE_RETIRE_ITEM_CHANNEL,
  SCHEDULE_SET_COMPLETION_CHANNEL,
  SCHEDULE_UPDATE_ITEM_CHANNEL,
  type ScheduleBridge,
  type ScheduleBridgePayload,
} from "./bridge/schedule-bridge";
export * from "./bridge/schedule-bridge";
import {
  createQuickToolsBridge,
  QUICK_TOOLS_GET_MEMO_CHANNEL,
  QUICK_TOOLS_SAVE_MEMO_CHANNEL,
  type QuickToolsBridge,
  type QuickToolsBridgePayload,
} from "./bridge/quick-tools-bridge";
export * from "./bridge/quick-tools-bridge";
import {
  ASSISTANT_CHATGPT_OAUTH_START_LOGIN_CHANNEL,
  ASSISTANT_CHATGPT_OAUTH_STATUS_CHANNEL,
  ASSISTANT_CHAT_RUN_CHANNEL,
  ASSISTANT_CONNECTOR_PROFILE_CHANNEL,
  ASSISTANT_DELETE_CONNECTION_CHANNEL,
  ASSISTANT_DESTINATION_PROFILE_CHANNEL,
  ASSISTANT_GRANT_CONTEXT_PERMISSION_CHANNEL,
  ASSISTANT_LIST_CONNECTIONS_CHANNEL,
  ASSISTANT_LIST_CONTEXT_STATE_CHANNEL,
  ASSISTANT_REVOKE_CONTEXT_PERMISSION_CHANNEL,
  ASSISTANT_RUN_EXTERNAL_SETTING_REVIEW_CHANNEL,
  ASSISTANT_RUN_NOTATION_REVIEW_CHANNEL,
  ASSISTANT_RUN_SETTING_REVIEW_CHANNEL,
  ASSISTANT_RUN_VOCABULARY_LOOKUP_CHANNEL,
  ASSISTANT_RUN_VOCABULARY_SUGGESTION_CHANNEL,
  ASSISTANT_SAVE_CONNECTION_CHANNEL,
  createAssistantBridge,
  type AssistantBridge,
  type AssistantBridgePayload,
} from "./bridge/assistant-bridge";
export * from "./bridge/assistant-bridge";
import {
  APP_SETTINGS_GET_CHANNEL,
  APP_SETTINGS_PROFILE_CHANNEL,
  APP_SETTINGS_SAVE_CHANNEL,
  INSPIRATION_SETTINGS_GET_WORK_CHANNEL,
  INSPIRATION_SETTINGS_SAVE_WORK_CHANNEL,
  MUSIC_SETTINGS_GET_WORK_CHANNEL,
  MUSIC_SETTINGS_PROFILE_CHANNEL,
  MUSIC_SETTINGS_SAVE_WORK_CHANNEL,
  UI_PREFERENCES_GET_CHANNEL,
  UI_PREFERENCES_SAVE_CHANNEL,
  YOUTUBE_MUSIC_CONNECTION_SAVE_CHANNEL,
  YOUTUBE_MUSIC_CONNECTION_STATUS_CHANNEL,
  createSettingsBridge,
  type SettingsBridge,
  type SettingsBridgePayload,
} from "./bridge/settings-bridge";
export * from "./bridge/settings-bridge";
import {
  LOCAL_MEDIA_SELECT_CHANNEL,
  SCENE_MUSIC_QUEUE_LIST_CHANNEL,
  SCENE_MUSIC_QUEUE_SEARCH_CHANNEL,
  SCENE_MUSIC_QUEUE_SELECT_CHANNEL,
  YOUTUBE_MUSIC_PROFILE_CHANNEL,
  YOUTUBE_MUSIC_SEARCH_CHANNEL,
  createMusicPlaybackBridge,
  type MusicPlaybackBridge,
  type MusicPlaybackBridgePayload,
} from "./bridge/music-playback-bridge";
export * from "./bridge/music-playback-bridge";
import {
  VERSION_COMPARE_WORK_SNAPSHOT_CHANNEL,
  VERSION_CREATE_WORK_SNAPSHOT_CHANNEL,
  VERSION_LIST_DOCUMENT_REVISIONS_CHANNEL,
  VERSION_LIST_WORK_SNAPSHOTS_CHANNEL,
  VERSION_READ_DOCUMENT_REVISION_CHANNEL,
  VERSION_RESTORE_DOCUMENT_REVISION_CHANNEL,
  createVersionBridge,
  type VersionBridge,
  type VersionBridgePayload,
} from "./bridge/version-bridge";
export * from "./bridge/version-bridge";
import {
  BACKUP_CREATE_CHANNEL,
  BACKUP_GET_STATUS_CHANNEL,
  BACKUP_RESTORE_CHANNEL,
  createBackupBridge,
  type BackupBridge,
} from "./bridge/backup-bridge";
export * from "./bridge/backup-bridge";
import {
  MIGRATION_RUN_LEGACY_REHEARSAL_CHANNEL,
  createMigrationBridge,
  type MigrationBridge,
} from "./bridge/migration-bridge";
export * from "./bridge/migration-bridge";

export type StudioBridge = PublishingBridge & {
  system: SystemBridge;
  workspace: WorkspaceBridge;
  structure: StructureBridge;
  fragments: FragmentsBridge;
  characters: CharactersBridge;
  loreEntries: LoreEntriesBridge;
  loreCandidates: LoreCandidatesBridge;
  loreForeshadowLinks: LoreForeshadowLinksBridge;
  plots: PlotsBridge;
  foreshadowing: ForeshadowingBridge;
  activity: ActivityBridge;
  schedule: ScheduleBridge;
  settings: SettingsBridge;
  musicPlayback: MusicPlaybackBridge;
  quickTools: QuickToolsBridge;
  assistant: AssistantBridge;
  version: VersionBridge;
  backup: BackupBridge;
  migration: MigrationBridge;
  editor: EditorBridge;
};

export type BridgeInvoke = (
  channel:
    | typeof RUNTIME_INFO_CHANNEL
    | typeof MANUSCRIPT_INPUT_PROFILE_CHANNEL
    | typeof MANUSCRIPT_DOCUMENT_PROFILE_CHANNEL
    | typeof MANUSCRIPT_FORMATTING_PROFILE_CHANNEL
    | typeof MANUSCRIPT_PREFLIGHT_PROFILE_CHANNEL
    | typeof MANUSCRIPT_PREFLIGHT_GET_SETTINGS_CHANNEL
    | typeof MANUSCRIPT_PREFLIGHT_SAVE_SETTINGS_CHANNEL
    | typeof MANUSCRIPT_EXPORT_TEXT_CHANNEL
    | typeof MANUSCRIPT_SELECT_TEXT_IMPORT_CHANNEL
    | typeof MANUSCRIPT_PERSISTENCE_PROFILE_CHANNEL
    | typeof MANUSCRIPT_SAVE_CHANGE_BATCH_CHANNEL
    | typeof MANUSCRIPT_SAVE_DOCUMENT_CHANGE_CHANNEL
    | typeof MANUSCRIPT_SAVE_FORMATTING_CHANNEL
    | typeof MANUSCRIPT_MOVE_RANGE_TO_EPISODE_CHANNEL
    | typeof MANUSCRIPT_UNDO_MOVE_RANGE_TO_EPISODE_CHANNEL
    | typeof MANUSCRIPT_GET_WORK_LAYOUT_SETTINGS_CHANNEL
    | typeof MANUSCRIPT_SAVE_WORK_LAYOUT_SETTINGS_CHANNEL
    | typeof MANUSCRIPT_STARTUP_RECOVERY_CHANNEL
    | typeof MANUSCRIPT_RESUME_CHECKPOINT_CHANNEL
    | typeof MANUSCRIPT_GET_CONTINUOUS_READING_PROGRESS_CHANNEL
    | typeof MANUSCRIPT_SAVE_CONTINUOUS_READING_PROGRESS_CHANNEL
    | typeof MANUSCRIPT_APPLY_STARTUP_RECOVERY_CHANNEL
    | typeof MANUSCRIPT_COMPLETE_CLOSE_REQUEST_CHANNEL
    | typeof WORKSPACE_CATALOG_CHANNEL
    | typeof WORKSPACE_GET_DOCUMENT_COMPLETION_CHANNEL
    | typeof WORKSPACE_COMPLETE_DOCUMENT_CHANNEL
    | typeof WORKSPACE_CLEAR_DOCUMENT_COMPLETION_CHANNEL
    | typeof WORKSPACE_FAVORITES_CHANNEL
    | typeof WORKSPACE_SET_FAVORITE_CHANNEL
    | typeof WORKSPACE_COVERS_CHANNEL
    | typeof WORKSPACE_SELECT_COVER_CHANNEL
    | typeof WORKSPACE_CREATE_FIRST_WORK_CHANNEL
    | typeof WORKSPACE_CREATE_WORK_CHANNEL
    | typeof WORKSPACE_CREATE_DOCUMENT_CHANNEL
    | typeof WORKSPACE_RENAME_WORK_CHANNEL
    | typeof WORKSPACE_RENAME_DOCUMENT_CHANNEL
    | typeof WORKSPACE_RETIRE_WORK_CHANNEL
    | typeof WORKSPACE_RETIRE_DOCUMENT_CHANNEL
    | typeof WORKSPACE_RETIRE_ALL_DOCUMENTS_CHANNEL
    | typeof WORKSPACE_MOVE_DOCUMENT_CHANNEL
    | typeof WORKSPACE_CREATE_DOCUMENT_FOLDER_CHANNEL
    | typeof WORKSPACE_RENAME_DOCUMENT_FOLDER_CHANNEL
    | typeof WORKSPACE_PLACE_DOCUMENT_IN_FOLDER_CHANNEL
    | typeof WORKSPACE_RETIRE_DOCUMENT_FOLDER_CHANNEL
    | typeof WORKSPACE_ACTIVATE_LOCATION_CHANNEL
    | typeof WORKSPACE_CAPTURE_RESUME_CHANNEL
    | typeof STRUCTURE_CREATE_EVENT_BLOCK_CHANNEL
    | typeof STRUCTURE_CREATE_ANCHORLESS_EVENT_CHANNEL
    | typeof STRUCTURE_MOVE_EVENT_BLOCK_CHANNEL
    | typeof STRUCTURE_LINK_EVENT_SOURCE_CHANNEL
    | typeof STRUCTURE_REPLACE_EVENT_SOURCE_CHANNEL
    | typeof STRUCTURE_RETIRE_EVENT_SOURCE_CHANNEL
    | typeof STRUCTURE_LIST_EVENT_BLOCKS_CHANNEL
    | typeof STRUCTURE_LIST_EVENT_RAIL_CHANNEL
    | typeof STRUCTURE_CREATE_SCENE_OVERRIDE_CHANNEL
    | typeof STRUCTURE_RELOCATE_SCENE_SEGMENT_CHANNEL
    | typeof STRUCTURE_LIST_SCENE_OVERRIDES_CHANNEL
    | typeof STRUCTURE_LIST_SCENE_PROJECTION_CHANNEL
    | typeof STRUCTURE_UPDATE_SCENE_RULE_SET_CHANNEL
    | typeof STRUCTURE_SET_SCENE_EVENT_OVERRIDE_CHANNEL
    | typeof STRUCTURE_RUN_SCENE_EXTRACTION_CHANNEL
    | typeof STRUCTURE_LIST_SCENE_EXTRACTION_CANDIDATES_CHANNEL
    | typeof STRUCTURE_DECIDE_SCENE_EXTRACTION_BOUNDARY_CHANNEL
    | typeof STRUCTURE_LIST_SCENE_ANNOTATIONS_CHANNEL
    | typeof STRUCTURE_DECIDE_SCENE_EXTRACTION_ANNOTATION_CHANNEL
    | typeof STRUCTURE_RUN_SCENE_DRAFT_CHANNEL
    | typeof STRUCTURE_LIST_SCENE_DRAFT_CANDIDATES_CHANNEL
    | typeof STRUCTURE_UPDATE_SCENE_DRAFT_CANDIDATE_CHANNEL
    | typeof STRUCTURE_PREPARE_SCENE_DRAFT_INSERTION_CHANNEL
    | typeof STRUCTURE_COMPLETE_SCENE_DRAFT_INSERTION_CHANNEL
    | typeof FRAGMENT_PROFILE_CHANNEL
    | typeof FRAGMENT_CAPTURE_CHANNEL
    | typeof FRAGMENT_LIST_CHANNEL
    | typeof FRAGMENT_UPDATE_CHANNEL
    | typeof FRAGMENT_RECORD_USE_CHANNEL
    | typeof FRAGMENT_RETIRE_CHANNEL
    | typeof CHARACTER_CREATE_CHANNEL
    | typeof CHARACTER_LIST_CHANNEL
    | typeof CHARACTER_UPDATE_CHANNEL
    | typeof CHARACTER_ADD_EVIDENCE_CHANNEL
    | typeof CHARACTER_RETIRE_CHANNEL
    | typeof CHARACTER_RELATION_CREATE_CHANNEL
    | typeof CHARACTER_RELATION_LIST_CHANNEL
    | typeof CHARACTER_RELATION_UPDATE_CHANNEL
    | typeof CHARACTER_RELATION_RETIRE_CHANNEL
    | typeof CHARACTER_EXTRACTION_RUN_CHANNEL
    | typeof CHARACTER_EXTRACTION_LIST_CHANNEL
    | typeof CHARACTER_EXTRACTION_DECIDE_CHANNEL
    | typeof CHARACTER_GENERATION_RUN_CHANNEL
    | typeof CHARACTER_GENERATION_LIST_CHANNEL
    | typeof CHARACTER_GENERATION_DECIDE_CHANNEL
    | typeof LORE_ENTRY_CREATE_CHANNEL
    | typeof LORE_ENTRY_LIST_CHANNEL
    | typeof LORE_ENTRY_UPDATE_CHANNEL
    | typeof LORE_ENTRY_ADD_EVIDENCE_CHANNEL
    | typeof LORE_ENTRY_RETIRE_CHANNEL
    | typeof LORE_CANDIDATE_CREATE_CHANNEL
    | typeof LORE_CANDIDATE_LIST_CHANNEL
    | typeof LORE_CANDIDATE_APPROVE_CHANNEL
    | typeof LORE_CANDIDATE_REJECT_CHANNEL
    | typeof LORE_FORESHADOW_LINK_CHANNEL
    | typeof LORE_FORESHADOW_LIST_CHANNEL
    | typeof LORE_FORESHADOW_UNLINK_CHANNEL
    | typeof PUBLISHING_PARTNER_CREATE_CHANNEL
    | typeof PUBLISHING_PARTNER_LIST_CHANNEL
    | typeof PUBLISHING_PARTNER_UPDATE_CHANNEL
    | typeof PUBLISHING_SUBMISSION_CREATE_CHANNEL
    | typeof PUBLISHING_SUBMISSION_LIST_CHANNEL
    | typeof PUBLISHING_SUBMISSION_UPDATE_CHANNEL
    | typeof PUBLISHING_CONTRACT_CREATE_CHANNEL
    | typeof PUBLISHING_CONTRACT_LIST_CHANNEL
    | typeof PUBLISHING_CONTRACT_UPDATE_CHANNEL
    | typeof PUBLISHING_PUBLICATION_CREATE_CHANNEL
    | typeof PUBLISHING_PUBLICATION_LIST_CHANNEL
    | typeof PUBLISHING_PUBLICATION_UPDATE_CHANNEL
    | typeof PUBLISHING_SETTLEMENT_CREATE_CHANNEL
    | typeof PUBLISHING_SETTLEMENT_LIST_CHANNEL
    | typeof PUBLISHING_SETTLEMENT_UPDATE_CHANNEL
    | typeof PUBLISHING_PAYMENT_CREATE_CHANNEL
    | typeof PUBLISHING_PAYMENT_LIST_CHANNEL
    | typeof PUBLISHING_PAYMENT_UPDATE_CHANNEL
    | typeof PUBLISHING_SOURCE_CREATE_CHANNEL
    | typeof PUBLISHING_SOURCE_LIST_CHANNEL
    | typeof PUBLISHING_RESEARCH_PREVIEW_CHANNEL
    | typeof PUBLISHING_RESEARCH_APPROVE_CHANNEL
    | typeof PUBLISHING_ASSISTANT_RUN_CHANNEL
    | typeof PUBLISHING_ASSISTANT_APPROVE_CHANNEL
    | typeof PUBLISHING_EVIDENCE_SET_LINKS_CHANNEL
    | typeof PUBLISHING_PARTNER_CSV_SELECT_CHANNEL
    | typeof PUBLISHING_PARTNER_CSV_APPLY_CHANNEL
    | typeof PUBLISHING_SUBMISSION_CSV_SELECT_CHANNEL
    | typeof PUBLISHING_SUBMISSION_CSV_APPLY_CHANNEL
    | typeof PUBLISHING_MAIL_CANDIDATE_LIST_CHANNEL
    | typeof PUBLISHING_MAIL_CANDIDATE_LINK_CHANNEL
    | typeof PUBLISHING_MAIL_CANDIDATE_UPDATE_CHANNEL
    | typeof PUBLISHING_MAIL_CANDIDATE_REVIEW_CHANNEL
    | typeof PUBLISHING_MAIL_CONNECTION_STATUS_CHANNEL
    | typeof PUBLISHING_MAIL_CONNECTION_CONNECT_CHANNEL
    | typeof PUBLISHING_MAIL_CONNECTION_SYNC_CHANNEL
    | typeof PUBLISHING_MAIL_CONNECTION_DISCONNECT_CHANNEL
    | typeof PUBLISHING_MAIL_SCHEDULE_STATUS_CHANNEL
    | typeof PUBLISHING_MAIL_SCHEDULE_SAVE_CHANNEL
    | typeof PLOT_CREATE_CHANNEL
    | typeof PLOT_LIST_CHANNEL
    | typeof PLOT_DEFAULT_BOARD_CHANNEL
    | typeof PLOT_MOVE_PLACEMENT_CHANNEL
    | typeof PLOT_SET_STORY_TIME_CHANNEL
    | typeof PLOT_UPDATE_CHANNEL
    | typeof PLOT_RETIRE_CHANNEL
    | typeof PLOT_CREATE_FROM_EVENT_CHANNEL
    | typeof PLOT_CREATE_EVENT_CHANNEL
    | typeof PLOT_LINK_EVENT_CHANNEL
    | typeof PLOT_UNLINK_EVENT_CHANNEL
    | typeof PLOT_EVENT_LINK_LIST_CHANNEL
    | typeof PLOT_LINK_SOURCE_CHANNEL
    | typeof PLOT_SOURCE_LIST_CHANNEL
    | typeof FORESHADOW_CREATE_LINE_CHANNEL
    | typeof FORESHADOW_LIST_LINES_CHANNEL
    | typeof FORESHADOW_UPDATE_LINE_CHANNEL
    | typeof FORESHADOW_RETIRE_LINE_CHANNEL
    | typeof FORESHADOW_POINT_PROFILE_CHANNEL
    | typeof FORESHADOW_CREATE_POINT_CHANNEL
    | typeof FORESHADOW_LIST_POINTS_CHANNEL
    | typeof ACTIVITY_LIST_WORK_CHANNEL
    | typeof ACTIVITY_EXPORT_RECORDS_CHANNEL
    | typeof ACTIVITY_GET_RECORDS_GOALS_CHANNEL
    | typeof ACTIVITY_SAVE_RECORDS_GOALS_CHANNEL
    | typeof ACTIVITY_GET_READTHROUGH_CHANNEL
    | typeof ACTIVITY_SAVE_READTHROUGH_CHANNEL
    | typeof ACTIVITY_START_SESSION_CHANNEL
    | typeof ACTIVITY_STOP_SESSION_CHANNEL
    | typeof ACTIVITY_START_FOCUS_CHANNEL
    | typeof ACTIVITY_STOP_FOCUS_CHANNEL
    | typeof ACTIVITY_GET_POMODORO_CHANNEL
    | typeof ACTIVITY_CONFIGURE_START_POMODORO_CHANNEL
    | typeof ACTIVITY_PAUSE_POMODORO_CHANNEL
    | typeof ACTIVITY_RESUME_POMODORO_CHANNEL
    | typeof ACTIVITY_RECONCILE_POMODORO_CHANNEL
    | typeof ACTIVITY_UPDATE_POMODORO_NOTE_CHANNEL
    | typeof ACTIVITY_STOP_POMODORO_CHANNEL
    | typeof SCHEDULE_LIST_WORK_CHANNEL
    | typeof SCHEDULE_LIST_CALENDAR_CHANNEL
    | typeof SCHEDULE_LIST_TODAY_CHANNEL
    | typeof SCHEDULE_CREATE_ITEM_CHANNEL
    | typeof SCHEDULE_UPDATE_ITEM_CHANNEL
    | typeof SCHEDULE_RETIRE_ITEM_CHANNEL
    | typeof SCHEDULE_SET_COMPLETION_CHANNEL
    | typeof QUICK_TOOLS_GET_MEMO_CHANNEL
    | typeof QUICK_TOOLS_SAVE_MEMO_CHANNEL
    | typeof ASSISTANT_CHATGPT_OAUTH_STATUS_CHANNEL
    | typeof ASSISTANT_CHATGPT_OAUTH_START_LOGIN_CHANNEL
    | typeof ASSISTANT_CHAT_RUN_CHANNEL
    | typeof ASSISTANT_LIST_CONTEXT_STATE_CHANNEL
    | typeof ASSISTANT_GRANT_CONTEXT_PERMISSION_CHANNEL
    | typeof ASSISTANT_REVOKE_CONTEXT_PERMISSION_CHANNEL
    | typeof ASSISTANT_DESTINATION_PROFILE_CHANNEL
    | typeof ASSISTANT_CONNECTOR_PROFILE_CHANNEL
    | typeof ASSISTANT_RUN_VOCABULARY_LOOKUP_CHANNEL
    | typeof ASSISTANT_RUN_VOCABULARY_SUGGESTION_CHANNEL
    | typeof ASSISTANT_RUN_EXTERNAL_SETTING_REVIEW_CHANNEL
    | typeof ASSISTANT_RUN_NOTATION_REVIEW_CHANNEL
    | typeof ASSISTANT_RUN_SETTING_REVIEW_CHANNEL
    | typeof ASSISTANT_LIST_CONNECTIONS_CHANNEL
    | typeof ASSISTANT_SAVE_CONNECTION_CHANNEL
    | typeof ASSISTANT_DELETE_CONNECTION_CHANNEL
    | typeof APP_SETTINGS_PROFILE_CHANNEL
    | typeof APP_SETTINGS_GET_CHANNEL
    | typeof APP_SETTINGS_SAVE_CHANNEL
    | typeof UI_PREFERENCES_GET_CHANNEL
    | typeof UI_PREFERENCES_SAVE_CHANNEL
    | typeof MUSIC_SETTINGS_PROFILE_CHANNEL
    | typeof MUSIC_SETTINGS_GET_WORK_CHANNEL
    | typeof MUSIC_SETTINGS_SAVE_WORK_CHANNEL
    | typeof INSPIRATION_SETTINGS_GET_WORK_CHANNEL
    | typeof INSPIRATION_SETTINGS_SAVE_WORK_CHANNEL
    | typeof YOUTUBE_MUSIC_CONNECTION_STATUS_CHANNEL
    | typeof YOUTUBE_MUSIC_CONNECTION_SAVE_CHANNEL
    | typeof YOUTUBE_MUSIC_PROFILE_CHANNEL
    | typeof YOUTUBE_MUSIC_SEARCH_CHANNEL
    | typeof LOCAL_MEDIA_SELECT_CHANNEL
    | typeof SCENE_MUSIC_QUEUE_SEARCH_CHANNEL
    | typeof SCENE_MUSIC_QUEUE_LIST_CHANNEL
    | typeof SCENE_MUSIC_QUEUE_SELECT_CHANNEL
    | typeof VERSION_LIST_DOCUMENT_REVISIONS_CHANNEL
    | typeof VERSION_READ_DOCUMENT_REVISION_CHANNEL
    | typeof VERSION_RESTORE_DOCUMENT_REVISION_CHANNEL
    | typeof VERSION_CREATE_WORK_SNAPSHOT_CHANNEL
    | typeof VERSION_LIST_WORK_SNAPSHOTS_CHANNEL
    | typeof VERSION_COMPARE_WORK_SNAPSHOT_CHANNEL
    | typeof BACKUP_GET_STATUS_CHANNEL
    | typeof BACKUP_CREATE_CHANNEL
    | typeof BACKUP_RESTORE_CHANNEL
    | typeof MIGRATION_RUN_LEGACY_REHEARSAL_CHANNEL,
  payload?:
    | EditorBridgePayload
    | WorkspaceBridgePayload
    | StructureBridgePayload
    | MusicPlaybackBridgePayload
    | FragmentBridgePayload
    | CharactersBridgePayload
    | LoreBridgePayload
    | PublishingBridgePayload
    | PlotsBridgePayload
    | ForeshadowingBridgePayload
    | ActivityBridgePayload
    | ScheduleBridgePayload
    | QuickToolsBridgePayload
    | AssistantBridgePayload
    | SettingsBridgePayload
    | VersionBridgePayload,
) => Promise<unknown>;

export type StudioBridgeCapabilities = Readonly<{
  fragments?: FragmentsBridge;
  foreshadowing?: ForeshadowingBridge;
  activity?: ActivityBridge;
  characters?: CharactersBridge;
  lore?: LoreBridge;
  assistant?: AssistantBridge;
  settings?: SettingsBridge;
  musicPlayback?: MusicPlaybackBridge;
  version?: VersionBridge;
  backup?: BackupBridge;
  migration?: MigrationBridge;
  plots?: PlotsBridge;
  structure?: StructureBridge;
  workspace?: WorkspaceBridge;
  system?: SystemBridge;
  editor?: EditorBridge;
  publishing?: PublishingBridge;
  schedule?: ScheduleBridge;
  quickTools?: QuickToolsBridge;
}>;

export function createStudioBridge(
  invoke: BridgeInvoke,
  listen: BridgeListen,
  capabilities: StudioBridgeCapabilities = {},
): StudioBridge {
  const lore = capabilities.lore ?? createLoreBridge(invoke);
  const publishing =
    capabilities.publishing ?? createPublishingBridge(invoke);

  return {
    system: capabilities.system ?? createSystemBridge(invoke),
    workspace: capabilities.workspace ?? createWorkspaceBridge(invoke),
    structure: capabilities.structure ?? createStructureBridge(invoke),
    fragments: capabilities.fragments ?? createFragmentsBridge(invoke),
    characters: capabilities.characters ?? createCharactersBridge(invoke),
    loreEntries: lore.loreEntries,
    loreCandidates: lore.loreCandidates,
    loreForeshadowLinks: lore.loreForeshadowLinks,
    ...publishing,
    plots: capabilities.plots ?? createPlotsBridge(invoke),
    foreshadowing:
      capabilities.foreshadowing ?? createForeshadowingBridge(invoke),
    activity: capabilities.activity ?? createActivityBridge(invoke),
    schedule: capabilities.schedule ?? createScheduleBridge(invoke),
    settings: capabilities.settings ?? createSettingsBridge(invoke),
    musicPlayback:
      capabilities.musicPlayback ?? createMusicPlaybackBridge(invoke),
    quickTools: capabilities.quickTools ?? createQuickToolsBridge(invoke),
    assistant: capabilities.assistant ?? createAssistantBridge(invoke),
    version: capabilities.version ?? createVersionBridge(invoke),
    backup: capabilities.backup ?? createBackupBridge(invoke),
    migration: capabilities.migration ?? createMigrationBridge(invoke),
    editor: capabilities.editor ?? createEditorBridge(invoke, listen),
  };
}
